### ISSUE TITLE
url route error 

### ISSUE THREAD

**Issue by bruceding** [flightphp/core#146]
I add a url , like: 
Flight::route('/test/name', function(){
    echo 'hello world!';
});

when I get it throw chrome(http://www.example.com/test/name) , response:
404 Not Found.

Request::init  here , I found 

if ($this->base != '/' && strlen($this->base) > 0 && strpos($this->url, $this->base) === 0) {
            $this->url = substr($this->url, strlen($this->base));
        }

why deal $this->url ?  I componet this, everything is ok .

Sorry to my poor English.

**Comment by kouts** [comment]
You must have an .htaccess file in order for routing to work:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]
```

**Comment by mikecao** [comment]
That line is there to check if you are running Flight under a subdirectory. If you are, then you don't need to include it in your routes. So instead of `Flight::route('/subdir/test')` you just do `Flight::route('/test')`.
