### ISSUE TITLE
PHP session and external libraries

### ISSUE THREAD

**Issue by dabiddo** [flightphp/core#163]
Hello, congrats on the framework, easy to use and very good documentation.

I have a few questions.

Is there any way I can use the PHP $_SESSION? I tried using it but with no luck, I also tried using the Flight::set, but it only works outside the ROUTE :(

Second question, I want to use the HybridAuth library, but don't know how to load external libraries, is this possible? I read the Docs, and I tried loading the library using the Flight::path, but no luck either, and there is no example on the docs.

**Comment by everflux** [comment]
There should be no problem using the $_SESSION - did you call session_start() ?
