### ISSUE TITLE
Simple controllers implementation for Flight

### ISSUE THREAD

**Issue by ghost** [flightphp/core#164]
Hi,

Have you thought about implementing simple controllers? I think flight is a good framework to implement small application, but the routing system is a little complicated to organize in something more complex...

Im using flight in a project and created a fork that supports simple controllers.

Controllers extends FlightController class, and has an array with the routes and methods.
Later, the controller can be installed calling like this:

Flight::controller('ClassController');

My fork: https://github.com/Th3DarKZI0N/flight

Maybe this could take a look!

Sorry for my bad english!!

Regards,
Gabriel

**Comment by gexeh** [comment]
@Th3DarKZI0N ,

I have setup the following test routes:

``` php
        public static $_routes = array(
            '*' => 'index',
            '/test' => 'test',
            '/@name/@id'=> 'user'
        );

        public function index() {
            echo 'Hello from Index.';
            return true;
        }

        public function test() {
            echo 'Hello from Test.';
        }

        public function user($name, $id){
            echo "hello, $name ($id)!";
        }
```

When visiting the following routes I get unexpected results;

www.example.com/ = 404 (why?)
www.example.com/test/ =  "Hello from Index.Hello from Test." (As expected)
www.example.com/gexeh/confused = "Hello from Index.hello, gexeh (confused)!" (As expected)

I believe the issue is caused by the "return true" for the wildcard i.e. proceed to the next match.

I have no idea how to fix this issue, could we get a fix?

**Comment by ghost** [comment]
I get the same behavior (404) when i'm doing something like:

``` php
class Greeting {
    public static function hello() {
        echo 'hello world!';
        return true;
    }
}

Flight::route('/', array('Greeting','hello'));
```

Returning false there is no problem...

I think this could  be a question for the Flight developer, maybe is a bug...

**Comment by mikecao** [comment]
When you return `true` it means you want to proceed to the next matched route. If there are no matches it returns a 404 as expected. Remember that routes are matched in order. If you want to have a catchall `*` that is always triggered, you should put it at the bottom of your list.

**Comment by gexeh** [comment]
Thanks for the responses. So to clarify Mike, if I put the wildcard at the bottom of the array it should return my route for "/"? I'm using thedarkzion's controller fork.

**Comment by mikecao** [comment]
You would have to return `true` from any routes that come before your catchall.

**Comment by gexeh** [comment]
Thanks Mike, it appears to be working as expected now;

``` php
        public static $_routes = array(
            '/test' => 'test',
            '/@name/@id'=> 'user',
            '*' => 'index'
        );

        public function index() {
            echo 'Hello from Index.';
        }

        public function test() {
            echo 'Hello from Test.';
            return true;
        }

        public function user($name, $id){
            echo "hello, $name ($id)!";
        }
```

As a side note, is development still ongoing? -  I'm considering using flight in a production environment.

**Comment by mikecao** [comment]
Flight is pretty stable at this point. There are still bug fixes and minor enhancements going on, but Flight was never meant to be a gigantic framework.

**Comment by gexeh** [comment]
Thanks Mike,

I'll give it a go and see how I get on.

The key challenge for me is how I go about displaying a view (page template if you like) which is to be called for all routes (wildcard), and then fill in a section of that view with the view from another defined route.

Currently I'm calling the following code for each defined route callback function;

``` php
        Flight::render('layout/navigation', array('page_id' => $page_id), 'page_navigation');
        Flight::render('account/login/login', array('login' => $login), 'page_content');
        Flight::render('layout/layout', array('page_id' => $page_id));
```

Surely this isn't the way to go? "layout/layout" is my page template and "layout/navigation" is the page navigation, "account/login/login" becomes the page content defined in the layout/layout view.

**Comment by cceconi** [comment]
@Th3DarKZI0N Your controllers are interesting but, since Flight is extensible, why don't your create your own extension and add a dependency to Flight with composer ?
I made this proposal because your implementation will not fit everyone needs and I believe it's better to let developers choose.

**Comment by ghost** [comment]
@cceconi I like the idea. Thanks!
