### ISSUE TITLE
Flight fails to match endpoints when inside another directory

### ISSUE THREAD

**Issue by sean256** [flightphp/core#166]
When flight is accessed from inside another directory it fails to match endpoints

api = where the api root is

Works:
https://localhost/api/endPoint
Flight::request()->url = /api/endPoint
Flight::request()->base = /api

Fails:
https://localhost/someOtherDirectory/api/endPoint
Flight::request()->url = /someOtherDirectory/api/endPoint
Flight::request()->base = /api

**Comment by willichan** [comment]
I am experiencing this issue, and would be willing to do any testing that may help.

OS:  Debian 3.2.65-1+deb7u2 x86_64
Web server:  Apache/2.2.22
PHP:  5.4.36-0

**Comment by mikecao** [comment]
Something doesn't look right. When running Flight under a subfolder, Flight will detect what that is and assign that to the `base` property. That way you can do routing without including the subfolder name, as in `Flight::route('/endPoint', ...)` minus the `/api` part. Then the base portion should be stripped from the `url`. So it should look like this:

Flight::request()->url = /endPoint
Flight::request()->base = /api

Double check your server configuration and make sure you're using the correct folder.

**Comment by willichan** [comment]
Traced the problem on my server to the recommended RewriteRule in the .htaccess file.  It works nice when installed in the root folder, but kills things when in a subdir.  I removed the RewriteRule, and everything works now.

**Comment by willichan** [comment]
In my case, it WAS a server config problem.  Someone else had put htaccess rules into the apache.conf config file without my knowledge.  They were causing problems with with .htaccess rules recommended in the install instructions.
