### ISSUE TITLE
request doesn't  recognize HTTP'/PATCH 

### ISSUE THREAD

**Issue by mrsoto** [flightphp/core#167]
In order to allow to update partial record in REST service HTTP prupose PATCH method.

http://tools.ietf.org/html/rfc5789

**Comment by mikecao** [comment]
Flight recognizes whatever the server sends in the REQUEST_METHOD or HTTP_X_HTTP_METHOD_OVERRIDE server variable. It does not filter or exclude any methods.

**Comment by mrsoto** [comment]
Hello,
I did submit a pull request from my commit rfc5789.

Fligth, as at as I understand, process http body as data if the method are
POST or PUT, PATCH isn't include in the evaluation.

Later,
Msoto

**Comment by mikecao** [comment]
Fixed in commit 10750b5ce321efe367d2dd7ab5f77049dae1ecd0.
