### ISSUE TITLE
AJAX requests cannot be cached

### ISSUE THREAD

**Issue by gera2ld** [flightphp/core#168]
I'm wondering why AJAX requests should not be cached when I saw this in the source code:

``` javascript
// Disable caching for AJAX requests
if ($request->ajax) {
    $response->cache(false);
}
```

jQuery AJAX has an option to choose whether the request should be cached, I think Flight might better have an option for this too.

**Comment by mikecao** [comment]
Fixed in commit b9dfda3fd692421832b650744343b4fce6fe27d6.
