### ISSUE TITLE
Fatal Error inside core/Dispatcher 

### ISSUE THREAD

**Issue by erisoftdevelop** [flightphp/core#169]
Hello I found this fatal error when I was testing flightf ramework ,I did use this example: 

Flight::route('/api/getName/@name/@id', function($name, $id){
    echo "hello, $name ($id)!";
});

The error comes when you invoke the route a set the parameters same like Flight::route declaration.
Ex.

www.xxxxx.com/api/getName/@name/@id

That produce this fatal error:

500 Internal Server Error

Missing argument 1 for {closure}(), called in xxxxxxxx/ws/flight/core/Dispatcher.php on line 160 and defined (2)

**Comment by mikecao** [comment]
Fixed in commit 1feeb95ff2f31fd93749bd0ea74c1ffedf884d33.
