### ISSUE TITLE
Throwing Error

### ISSUE THREAD

**Issue by frederichoule** [flightphp/core#170]
Is there any way to throw an error by myself so it gets handled by the Flight::map('error') ?

Something like Flight::error(); that would trigger the error map.

**Comment by frederichoule** [comment]
Sorry, just found "Flight::error" somewhere in the docs.

**Comment by frederichoule** [comment]
I am reopening as it seems Flight isn't catching exceptions I throw, either thru Flight::error(new Exception('something')), or simply throwing an exception.

They are not routed to Flight::map('error').

**Comment by mikecao** [comment]
What output are you getting?

This works fine for me:

``` php
Flight::map('error', function($error) {
    echo '<h1>ERROR: '.$error->getMessage().'</h1>';
});

Flight::route('/error', function(){
    throw new Exception('oh no!');
});

Flight::route('/error2', function(){
    Flight::error(new Exception('so bad!'));
});
```

**Comment by frederichoule** [comment]
You are right. Sorry about that, the error was in my map(error).

Awesome framework btw! Been using it for a few months now, it's on 10+ websites I made.
