### ISSUE TITLE
better autoload docs

### ISSUE THREAD

**Issue by Conver** [flightphp/core#174]
Would be great to get the autoload better doc'ed

**Comment by jimlei** [comment]
Use [Composer](https://getcomposer.org/) and you don't have to worry about autoloading

**Comment by Conver** [comment]
how so?

Been thinking about starting to use it, but so far there haven't been a real reason for me.

**Comment by jimlei** [comment]
When using composer you just list your projects dependencies (or do a composer require mikecao/flight" and composer handles installing them and setting up an autoloader for you. The autoloader will be created after the dependencies own specs, so it will work no matter what standards they are using (psr0, psr4, custom).

Then in your script you just do

``` php
require 'vendor/autoload.php';

Flight::route('/', function(){
    echo 'hello world!';
});

Flight::start();
```

**Comment by ghost** [comment]
@Conver There is no reason not to use Composer. Not only can it handle dependencies, it can also do autoloads and includes (assuming you're not using OOP) for you.

**Comment by mikecao** [comment]
Install instructions have been updated to include Composer.
