### ISSUE TITLE
Get Instance of Flight within class

### ISSUE THREAD

**Issue by JustSteveKing** [flightphp/core#176]
Ok I am new to Flight - but so far so good. I am just trying to get my head around how I can do certain things (like I would with Slim PHP or Silex).

For example I have managed to get my DB working with : `Flight::register("db", "App\Query");`
However I want to pass this into my Model now, so I can have my BaseModel and then singular Models.

Usually in something like Slim I would use : `$this->app = \Slim::getInstance();` However after having a look through the docs for Flight I cannot see a method which would provide a similar functionality. Has anybody tried this? Should I build my own? Or am I just missing something in the Docs ....

All I want to do is to add Flight into the scope of my Class !!

I have thought of a few ways which may work - _none tested yet_

`Flight::route("/route", array("App\Controllers\RouteController", "routeAction"), use(Flight));`

**Comment by mikecao** [comment]
If you are using Flight statically, then it is already available everywhere globally. In your controllers you would just call `Flight::db()`. If you still need to get an app instance for some reason, you can use the undocumented method `$app = Flight::app()`.

**Comment by JustSteveKing** [comment]
Perfect! Thanks Mike! Might I just say also that Sparrow is amazing! I am trying to integrate it into Flight as an ORM for my latest project.

~~Any advice on integrating Sparrow into Flight in the best way?~~

**EDIT** Have managed to get this done in a way that makes sense with Flight and Sparrow
