### ISSUE TITLE
No 404 response header is sent when using custom 404 error page

### ISSUE THREAD

**Issue by digi-coder** [flightphp/core#179]
When I override the notFound method by using the map method, as explained in the docs, Flight correctly displays the custom 404 error page but then it no longer sends a 404 response header. I seem to be getting a 200 response instead. Without overriding, Flight correctly sends the 404 response header, along with its generic 404 error message. Is this normal/by design? I tried using:

```
Flight::map('notFound', function(){
    // Display custom 404 page
    include 'errors/404.html';
});
```

and

```
Flight::map('notFound', function(){
    // Display custom 404 page
    Flight::redirect('/new/location', 404);
};
```

and

```
Flight::map('notFound', function(){
    // Display custom 404 page
    Flight::view()->display('@default/errors/404.twig');  
});
```

**Comment by mikecao** [comment]
Since you are overriding the default functionality, you need to send the right response code yourself. You can do something like this:

``` php
Flight::map('notFound', function() {
    echo '<h1>404 Not found</h1>';

    Flight::stop(404);
});
```

**Comment by digi-coder** [comment]
Ah...that works! 

Thank you Mike.
