### ISSUE TITLE
Use nikic/FastRoute for routeparsing

### ISSUE THREAD

**Issue by andreas-bergstrom** [flightphp/core#183]
Have you considered using nikic/FastRoute (https://github.com/nikic/FastRoute) for route parsing? Since Flight doesn't support route groups or such, it shouldn't be much work but probably improve the routing performance a lot. Would it be worth submiting a PR or just a waste of time?

Thanks for a great little gem (and keep it small!)!

**Comment by mikecao** [comment]
The main problem is that Flight's url parameter format is completely different, `/user/@id` versus `/user/{id}`. That would be a major switch for users. But I did read the blog post where he discussed performance and there are some good ideas in there which I can probably incorporate into Flight in the future. However, FastRoute by itself doesn't support a couple Flight features like optional groups `/user(/name(/id))` or the splat `/user/*`. Flight's router is already really fast itself, so I don't think it's worth switching just for a small performance gain and lose functionality.
