### ISSUE TITLE
Nested Views

### ISSUE THREAD

**Issue by lfelisiak** [flightphp/core#186]
Hi, How can i create a nested view i.e 

we got a default.php file which have {$header} and in header.php we have {$logo_and_info} {$nav} and in nav.php we have {$nav_main} {$nav_top} . We are unable to pass the nested template from $nav_top and $nav_main through $nav and through $header  its some way to pass a "rendered" template to a .php template without renderit ? i.e (Flight::render('body/content/nav.php',Flight::getTemplate('body/content/nav_top.php',null,'nav_top'),'nav'); ? 

Thanks

**Comment by mikecao** [comment]
The second parameter takes an array of key/value pairs. You're using `getTemplate`, which just returns a string.

**Comment by lfelisiak** [comment]
Yes, i noted it, so im passing an array key=>val with val = Flight::view()->fetch() to handle the thing and its working as expected.
