### ISSUE TITLE
Routing string and function ordering 

### ISSUE THREAD

**Issue by fatihmert** [flightphp/core#190]
Hello,

I show to you by example;

This is code work;
Flight::route('/blog(/@year(/@month(/@day)))', function($year, $month, $day){});

But this is not working
Flight::route('/blog(/@year(/@day)(/@month))', function($year, $month, $day){});

Actually, I want dynamic seo url. I can't
If I change route pattern strings, function doesn't work. Function of parameters because of its ordering.

**Comment by mikecao** [comment]
Your second route doesn't work because it's not valid. Optional parameters need to be nested within each other, you can't have something like `(/@day)(/@month)`. I don't understand what you are trying to match. Do you have some example urls?

**Comment by fatihmert** [comment]
Ohh, I am sorry.
It's ok.
