### ISSUE TITLE
Call to private Requests::__construct() - register requests class

### ISSUE THREAD

**Issue by fatihmert** [flightphp/core#191]
Hello,

I want register this class to flight, http://requests.ryanmccue.info/

```
require_once 'lib/Requests.php'; //Request s

Flight::register('requests',"Requests");
$requests = Flight::requests();

//use example
//$requests->get('http://ryanmccue.info/', array('Accept' => 'text/html'));
```

Error this;
`Fatal error: Call to private Requests::__construct() from context 'flight\core\Loader' in /opt/lampp/htdocs/flightphp-learn/flight/core/Loader.php on line 123`

If It can be override flightphp **request** class, It's ok.

Thank you for interest.

**Comment by philo23** [comment]
It looks like methods on that class are [used statically](https://github.com/rmccue/Requests/blob/aa2168ed0f625ea191e9b0c37c7a43e513e7b53a/library/Requests.php#L93), so I don't think it would make sense to register it with Flight.

If you're using composer you're better off installing Requests that way and then you can just use the class without having to load or register it.

**Comment by fatihmert** [comment]
Hmm, @philo23 thank you.
I am not using composer.

**Comment by fatihmert** [comment]
So @philo23 
How can I do get sample url address with **flight** request method?
Can you show me a sample pattern?

Thank you again.

**Comment by tamtamchik** [comment]
@fatihmert `Flight::request` return you request from the browser to your application. In other words, if your user visits `/` it will give you all information about this request, like headers, path, method, parameters passed, etc.

**Comment by fatihmert** [comment]
@tamtamchik ok. I understood.

Thank you for fast answer.

**Comment by tamtamchik** [comment]
@fatihmert try this out. You don't need to do extra lines to make it work with Flight. It should work out of the box.

``` php
require_once 'lib/Requests.php'; //Request 

Requests::get('http://ryanmccue.info/', array('Accept' => 'text/html'));
```

Also as a tip. Try [Guzzle](http://docs.guzzlephp.org/en/latest/).

**Comment by gerbz** [comment]
In what situation would you register a class vs just including/using it as is?
