### ISSUE TITLE
How to implement URL aliases?

### ISSUE THREAD

**Issue by ymakux** [flightphp/core#195]
Hello
I'm building a micro cms using Flight. Every page may have an URL alias, say something like "post123.html". Also I have system route '/page/@page_id'. If aliases are enabled, everything under page/@page_id must be redirected to its appropriate alias. How to do that?

**Comment by mikecao** [comment]
Is this what you mean?

``` php
Flight::route('/page/@page_id, function($page_id){
  Flight::redirect("/{$page_id}.html");
});
```

**Comment by ymakux** [comment]
Yes, something like this. But I'm looking for more elegant solution. I believe it can be done in .htaccess... Maybe you can point me in the right direction

**Comment by mikecao** [comment]
Rewrite rules are outside the scope of the framework. I would just look for some example `.htaccess` files online.
