### ISSUE TITLE
Flight::app() returns null if no method has been called previously

### ISSUE THREAD

**Issue by magnus-eriksson** [flightphp/core#200]
If you call `Flight::app()` before any other method in the facade, you get `null` back since it's the `Flight::__callStatic()` method that creates the instance.

I propose to let the `Flight::app()` method create the instance instead so we can use the Flight class as a facade and factory class.

**Comment by mikecao** [comment]
Fixed in commit 486ec7c689cbac4d60a2a76e32d32dc84e9f5189.
