### ISSUE TITLE
服务器不支持URL重写、也不支持命名空间怎么办

### ISSUE THREAD

**Issue by gzu-liyujiang** [flightphp/core#202]
Flight的确是个好东西，文档也很详细，可惜只支持PHP5.3+，还要求要服务器支持URL重写。捣鼓了N久，最后吸取了其中的部分精华，改了个版本：https://github.com/gzu-liyujiang/FlightLite

**Comment by ymakux** [comment]
用英文写

**Comment by gzu-liyujiang** [comment]
ymakux, Are you Chinese? My English is very very very bad, Only translated by Google. Almost able to read, but not to write.
