### ISSUE TITLE
Auto JSON decode

### ISSUE THREAD

**Issue by ghost** [flightphp/core#207]
Hi there,

Firstly - great work on Flight - love the framework!

I have a problem with accessing json data from the body of a post request. As per the documentation and the code, if I set the content type of the request correctly, the body should be automatically parsed to json and the data property set.  However, unless I do this myself, it does not actually work like this. 

To test/illustrate I added a simple router to my api with the following code:

Flight::route('/jsonissue', function(){

```
$flightData = Flight::request()->data;
$myOwnData = json_decode(Flight::request()->getBody(), true);
$testResponse['flight.data'] = $flightData;
$testResponse['own.data'] = $myOwnData;
Flight::json($testResponse);
```

});

I use runscope to test and here is the test request:

![image](https://cloud.githubusercontent.com/assets/10963583/10009680/01afeef0-60e1-11e5-8abb-31a852562ca1.png)

And then the response:

![image](https://cloud.githubusercontent.com/assets/10963583/10009677/f608e55c-60e0-11e5-9cf5-ef7fafebed36.png)

Hope this illustrates the problem?
is there some config setting I need to set/unset?

Regards
Heinz

**Comment by mikecao** [comment]
It is because `Flight::request()->data` is not an array, but an object called a Collection, that lets you access data via array indexes or properties. If you want the raw data as an array you can do `Flight::request()->data->getData()`.
