### ISSUE TITLE
Confusing to create REST with POST method

### ISSUE THREAD

**Issue by amrishodiq** [flightphp/core#209]
Hi, I'm writing a REST service with Flight. It seems promising. It's really good to use Flight for REST service with GET requests. But when it came to POST request, for example for a login function like this:

```
<?php
require 'flight/Flight.php';
require 'api.php';

Flight::route('POST /login', 'login');

Flight::start();
?>
```

Then in api.php I wrote this:

```
function login() {
    $username = $_POST['username'];
    $password = $_POST['password'];

    echo json_encode(array(
        "code"=>0,
        "message"=>"Succeed",
        "data"=>array(
            "username"=>$username,
            "realname"=>"Amri Shodiq"
        )
    ));
}
```

It works somehow when the POST request came with complete data (username and password). 
However, when I send only username, then we'll have:

```
<h1>500 Internal Server Error</h1>
<h3>Undefined index: password (8)</h3>
```

Which is true, because the password is not sent. But, I'd like to have my own request validation method, in order to give JSON formatted response like below.

```
{
  "code":1,
  "message":"Missing argument: password"
}
```

 Is it possible? How to do that correctly? I don't see the documentation talking about how to deal with POST request in further detail.

**Comment by mikecao** [comment]
That is not a Flight problem but a general PHP error. You're trying to access a key that doesn't exist so PHP is throwing an error. So you can either:
1) Disable strict error reporting in PHP
2) Or check if the key exists first using `isset($_POST['password'])`

**Comment by amrishodiq** [comment]
Hi Mike, 
Thnaks for the quick response.
Yes, I've implemented as you suggest. 
I rewrote the code so I now have it like this:

```
function login() {
    $missingParameters = array();
    if (!isset($_POST['username'])) {
        array_push($missingParameters, 'username');
    }
    if (!isset($_POST['password'])) {
        array_push($missingParameters, 'password');
    }
    reportMissingParameters($missingParameters);

    $username = $_POST['username'];
    $password = $_POST['password'];

    Flight::json(array(
        "code"=>0,
        "message"=>"Succeed",
        "data"=>array(
            "username"=>$username,
            "realname"=>"Amri Shodiq"
        )
    ));
}

function reportMissingParameters($missingParameters) {
    $parameters = implode(", ", $missingParameters);
    echo json_encode(array(
        "code"=>1,
        "message"=>"Missing parameter: ".$parameters.".",
        "data"=>null
    ));
    exit();
}
```

It works very good. But somehow, I see this part:

```
    if (!isset($_POST['username'])) {
        array_push($missingParameters, 'username');
    }
    if (!isset($_POST['password'])) {
        array_push($missingParameters, 'password');
    }
```

is a bit clumsy. It should be better written with code like this:

```
function validateEmptiness($varArray) {
    foreach ($varArray as $value) {
        if (!isset($value) || $value == null) {
            return false;
        }
    }
    return true;
}
```

Then, I tested with the same condition I send POST request with username parameter but without password parameter. And the result is:

```
<h1>500 Internal Server Error</h1>
<h3>Undefined index: password (8)</h3>
<pre>#0 /Users/amrishodiq/Sites/existing/api.php(6): flight\Engine->handleError(8, 'Undefined index...', '/Users/amrishod...', 6, Array)
#1 /Users/amrishodiq/Sites/existing/flight/core/Dispatcher.php(160): login()
#2 /Users/amrishodiq/Sites/existing/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction('login', Array)
#3 /Users/amrishodiq/Sites/existing/flight/Engine.php(312): flight\core\Dispatcher::execute('login', Array)
#4 /Users/amrishodiq/Sites/existing/flight/core/Dispatcher.php(191): flight\Engine->_start()
#5 /Users/amrishodiq/Sites/existing/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#6 /Users/amrishodiq/Sites/existing/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#7 /Users/amrishodiq/Sites/existing/flight/Engine.php(64): flight\core\Dispatcher->run('start', Array)
#8 /Users/amrishodiq/Sites/existing/flight/core/Dispatcher.php(191): flight\Engine->__call('start', Array)
#9 /Users/amrishodiq/Sites/existing/flight/core/Dispatcher.php(191): flight\Engine->start()
#10 /Users/amrishodiq/Sites/existing/flight/Flight.php(65): flight\core\Dispatcher::invokeMethod(Array, Array)
#11 /Users/amrishodiq/Sites/existing/index.php(10): Flight::__callStatic('start', Array)
#12 /Users/amrishodiq/Sites/existing/index.php(10): Flight::start()
#13 {main}</pre>
```

So, in this time I cancel the last step and make a note. I hope I would have a time to dig deeper.
I'll need to find out a way to escape from Flight's Dispatcher's callFunction method.
Thanks Mike Cao for your support.

**Comment by shaneshuford** [comment]
These are PHP questions, not Flight questions. Your json encode function is
still tring to encode a variable that dosnt exists.

```
$something=reportMissingParameters($missingParameters);
```

Check if there is something in $something. If so, give a different
response, and don't call this:

```
$username = $_POST['username'];
$password = $_POST['password'];
```

**Comment by amrishodiq** [comment]
Sorry I was having difficulty accesing Github lately.
Wll, Shaneshuford, I'm afraid you've confused by the code. exit() function in reportMissingParameters() make it stop there. So the json_encode will never reached.
