### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by gerbz** [flightphp/core#211]
I'm using flight to build a simple rest API.  Any recommendations for handling authentication?

**Comment by erlingormar** [comment]
I've wondered about the same thing, I built an API with another MVC framework but Flight kicks it's a*\* so I want to rewrite it and add authentication :)

**Comment by mikecao** [comment]
I think you can accomplish a lot with the built in functionality. For instance you can use filters like `Flight::before('start', $doSomeAuthCheck)`, or register your own class like `Flight::register('auth', 'YourAuthClass')` and then call it when needed, `Flight::auth()->checkLogin()`.

You can also use some third pary library like the Symfony authentication model and register it just like above.
