### ISSUE TITLE
Hope matchUrl to be case-sensitive

### ISSUE THREAD

**Issue by ycrao** [flightphp/core#214]
I use flight to build a small website. When I browse uppercase and lowercase mixed urls , I will get the same pages. Like these URLs :

```
http://flight.dev/test/index.html
http://flight.dev/test/index.HTML
http://flight.dev/TEST/Index.html
```

Hope matchUrl to be case-sensitive.

**Comment by mikecao** [comment]
Now available in latest commit 7fd3594ac7409cdacddc8e6609d0dea58dd5b5c9. You can now do:

``` php
Flight::set('flight.case_sensitive', true)
```
