### ISSUE TITLE
flight+medoo error!

### ISSUE THREAD

**Issue by ztd** [flightphp/core#217]
flight+medoo use register methods error!help

**Comment by ztd** [comment]
flight+medoo新用Flight::register方法，medoo出现找不到quote方法，不能正常使用，怎么回事?

**Comment by ycrao** [comment]
不知道，你咋用的，我反正用的好好的

**Comment by ztd** [comment]
require 'flight/Flight.php';
require 'medoo.php';

Flight::register('db', 'medoo', array('database_type'=>'sqlite', 'database_file'=>'data.db'));
Flight::route('/', function(){
    $db = Flight::db();
    $result = $db->select('table', '*', array('id'=>1));
    var_dump($result);
});

Flight::start();

Fatal error: Call to a member function query() on a non-object in /Users/ztd/PhpstormProjects/flight/medoo.php on line 167

**Comment by ycrao** [comment]
@ztd 你这哪里能直接这样用，请参考[flight-app-demo](https://github.com/xubodreamsky/flight-app-demo/)
推荐使用Flight::map

**Comment by ztd** [comment]
@ycrao 谢谢，我已找到解决方法，要在数组参数上再嵌套一个数组：
Flight::register('db', 'medoo', array(array('database_type'=>'sqlite', 'database_file'=>'data.db')));

**Comment by FarhanShares** [comment]
I'm having the same issue still now, is there any solution?
