### ISSUE TITLE
PHTML Views

### ISSUE THREAD

**Issue by rsenses** [flightphp/core#222]
I like to use .phtml in views. If i try this:

``` php
echo Flight::view()->render('index.phtml')
```

I get the error:
Template file not found: index.phtml.php. (0)

The solution is very simple, in the file View.php change line 154 from:

``` php
if ((substr($file, -4) != '.php')) {
```

to:

``` php
if (substr($file, -4) !== '.php' && substr($file, -6) !== '.phtml') {
```

Could you please add it to next release?
Thanks

**Comment by mikecao** [comment]
Now available in the commit cabbb25fcc5c80c5b5279145c508966e1e5e76e5. You can set the config value `flight.views.extension` to whatever you want. The default is still `.php`.
