### ISSUE TITLE
Add a tag to corresponding version change

### ISSUE THREAD

**Issue by tamtamchik** [flightphp/core#224]
Can you please along with changing version in [VERSION](../blob/master/VERSION) file add corresponding tag to [Releases](../releases). It'll update composer database and will be reflected here: https://packagist.org/packages/mikecao/flight 

It will also allow to install those versions via Composer. Right now latest version available via composer is **v1.2.13** but in fact latest version **v1.2.18**

Thanks.

**Comment by mikecao** [comment]
Thanks, I always forget to do that. Tag pushed.
