### ISSUE TITLE
PHP 7 / Throwable

### ISSUE THREAD

**Issue by meanprogramming** [flightphp/core#229]
Is there a PHP 7 version in the works? The error handling [has changed quite a bit](https://trowski.com/2015/06/24/throwable-exceptions-and-errors-in-php7/).

**Comment by mikecao** [comment]
Looks like the only thing to do is catch the new Throwable/Error classes. Should be doable.

**Comment by mcon2711** [comment]
Hi, I am just wondering whether php flight works with php7? 
If not when will the update be released?

**Comment by GJNilsen** [comment]
Im running Flight right out of the box on a PHP 7 server, did absolutely no changes to it at all.

**Comment by mcon2711** [comment]
Thanks, error work as well?

**Comment by GJNilsen** [comment]
I dont know. I code without making errors :laughing:

**Comment by tamtamchik** [comment]
@yuppielabel AWESOME! :trollface:

**Comment by mikecao** [comment]
Fixed in f3fa0513fe2e1994923793b85c593b7f2b644001.
