### ISSUE TITLE
Wrong htaccess rule add ignore images

### ISSUE THREAD

**Issue by Hexodus** [flightphp/core#230]
With the current .htaccess rules when an image is missing the page rendering is blocked. The browser console shows `net::ERR_TOO_MANY_REDIRECTS`

In my opinion this the proper .htaccess should be like this:

```
RewriteEngine On
RewriteRule \.(jpg|jpeg|png|gif|bmp)$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]
```

The result with missing images is drastically faster. IMO it doesen't make sense to redirect images to index.php anyways. 

By the way: your framework is great. This is exactly what I need. Thanks a lot ;)

**Comment by mikecao** [comment]
Wouldn't the problem exists for ANY file that doesn't exist on the server? Not sure why you're getting the redirect issue. It should just go to the index.php, which should immediately return a 404.

**Comment by Hexodus** [comment]
I admit that this may be dependent from the server configuration. Currenty I'm using it on my local PC with xampp. Have you tested this with missing images? I'm curious if `net::ERR_TOO_MANY_REDIRECTS` happens only on my machine.

**Comment by mikecao** [comment]
Any request that isn't matched by the rewrite conditions will be passed on to the index.php controller. From there Flight will look for a route to match the request and return 404 if it's not found. So `/missing`, or `/missing.jpg`, or `/missing.txt` are all the same thing.
