### ISSUE TITLE
Generate routes from an array

### ISSUE THREAD

**Issue by mastermindg** [flightphp/core#232]
I'm trying to generate a set of routes from an array. 

**How do I pass the array element value without it being statically defined in the route?**

``` php
// Build routes
    foreach($array as $element) {
    Flight::route('/' . $element . '/delete/@id', function($id){
        echo "Thanks for deleting: " . $element . " " . $id;
    });
    Flight::route('/' . $element . '/list', function(){
        echo "Here's a list of: " . $element;
    });
   }
```

**Comment by mikecao** [comment]
Not sure what you mean by statically defined. Maybe you're talking about passing variables to the anonymous function? Then you need to use the `use` keyword:

``` php
function () use ($element) {
    echo "$element is from the parent scope.";
}
```

**Comment by rdkempt** [comment]
`$route` won't be accessible in the routes after you've defined them like this (like in your sample code), but below is some code that will accomplish what you want:

``` php
Flight::map('generateRoutes', function($routes) {
    foreach ($routes as $route) {
        // Route for deleting
        Flight::route("/$route/delete/@id", function($id) {
            echo "Thanks for deleting: " . $id;
        });

        // Route for lists
        Flight::route("/$route/list", function() {
            echo "Here's a list of: " . explode('/', Flight::request()->url)[1];
        });
    }
});

$list = array("apples", "oranges");
Flight::generateRoutes($list);
```

I used the URL to retrieve which list we were looking at, you could also inspect the route information and use params to get the same information.

**Comment by mastermindg** [comment]
Thanks! Works perfectly!
