### ISSUE TITLE
JSON content type with specified charset

### ISSUE THREAD

**Issue by hkusulja** [flightphp/core#233]
PHP output header should b with charset part also

header('Content-type:application/json;charset=utf-8');

and not as it is now inside Engine.php
header('Content-type:application/json');

**Comment by mikecao** [comment]
The default charset for json is utf-8. It will still work without it.

**Comment by hkusulja** [comment]
It depends on a client / browser, 95% of applications specifies it as utf-8, so it is explicit, just edit this one line to fix this.

**Comment by mikecao** [comment]
Commit b96aaa79677635d2d81a0f1fda357903a5334918
