### ISSUE TITLE
Return View HTML

### ISSUE THREAD

**Issue by OwenMelbz** [flightphp/core#234]
Hi, Love the library thank you.

But I'm struggling to solve 1 little thing.

I need to return the rendered html from a View that I'm creating,

I've tried `Flight::fetch` and assigning `Flight:render` to a variable, but not getting the desired effect. How would I go about this?

Thanks

**Comment by tamtamchik** [comment]
@OwenMelbz This one works for me:

``` php
$result = Flight::view()->fetch('template', ['var' => 'value']);
```

**Comment by OwenMelbz** [comment]
Perfect! thank you so much!
