### ISSUE TITLE
Issue with <!DOCTYPE html> in multi level route

### ISSUE THREAD

**Issue by agodlydeciple** [flightphp/core#235]
When using a route like /about or / or /contact - the page renders just find using bootstrap. However, when using a multi-level route like /projects/photos - bootstrap fails to render.

Upon using the browser inspection tool (right click --> inspect in chrome) it shows that there are no errors for a single level route (/about).  But for a multi level route there is an error and it highlights the '<' of the <!DOCTYPE html> line. 
![image](https://cloud.githubusercontent.com/assets/683837/12590004/6066ce84-c426-11e5-84db-4f80a04bcf23.png)
![image](https://cloud.githubusercontent.com/assets/683837/12590077/b67a570a-c426-11e5-895a-1ddaae20122c.png)

the way I am doing the routes is:

``` php
Flight::route('*', array('Layout', 'buildLayout')); 
class Layout{
    public static function buildLayout(){
      //> script / css includes
      Flight::render('head', array('whatis' => 'stuff inside head tag'), 'head_content');

      //> build nav bar
      Flight::render('nav', array('site_name' => 'Bootstrap Template'), 'nav_content');

      //> build page Data
      Flight::render('page', array('whatis' => 'dynamic page content'), 'page_content');

      //> build full layout
      Flight::render('layout', array('show_footer' => 'yes'));
    }
  }
```

Does anyone have any thoughts as to what I may be doing wrong?

**Comment by rdkempt** [comment]
It sounds like you are including the Bootstrap CSS file with a relative path instead of an absolute one. Can you show the HTML you're using to include the CSS?

**Comment by agodlydeciple** [comment]
I am including it as a relative path to the index.php file.

``` html
<!-- this data sits in head.php to be 'echoed' in the layout.php file -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1,chrome=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

<link rel="stylesheet" href="./framework/css/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="./framework/css/bootstrap-theme.min.css" type="text/css">
<link rel="stylesheet" href="./framework/css/source-code-pro.css" type="text/css">
<link rel="stylesheet" href="./framework/css/style.css" type="text/css">
```

``` php
// this code renders that head content in the layout
//> script / css includes
Flight::render('head', array('whatis' => 'stuff inside head tag'), 'head_content');
```

``` php
//>Layout.php
<!DOCTYPE html>
<html>
  <head>
    //> data from the head.php file
    <?php echo $head_content; ?>
    <title>Bootstrap Template</title>
  </head>
  <body>
    <?php echo $nav_content; ?>

    <div class="container">
      <?php echo $page_content; ?>
    </div>
    <?php if($show_footer == "yes"){?>
      <footer class="footer footer-font">
                <div class="container">
                    <p class="text-muted">&copy; <?php echo date("Y") . " " . $site_name; ?> </p>
                </div>
        </footer>
    <?php } ?>
    <!-- Bootstrap core JavaScript ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="./framework/js/bootstrap.min.js"></script>

  </body>
</html>
```

and to restate my original comment that opened this issue - this code works without error for single path routes (i.e. /about) but it errors with multi-path routes (i.e. /about/me)

Thanks!

**Comment by rdkempt** [comment]
Axe the dots and use the absolute path, I imagine that will resolve the issue. The web browser is looking for domain.com/framework/ when you're loading "single level routes" like domain.com/foo and domain.com/bar but when you're loading up a "multi level route" like domain.com/foo/bar it's looking for domain.com/foo/framework which doesn't exist.

**Comment by agodlydeciple** [comment]
gave that a shot and it still wasn't working

``` html
<link rel="stylesheet" href="framework/css/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="framework/css/bootstrap-theme.min.css" type="text/css">
<link rel="stylesheet" href="framework/css/source-code-pro.css" type="text/css">
<link rel="stylesheet" href="framework/css/style.css" type="text/css">
```

even tried:

``` html
<link rel="stylesheet" href="/framework/css/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="/framework/css/bootstrap-theme.min.css" type="text/css">
<link rel="stylesheet" href="/framework/css/source-code-pro.css" type="text/css">
<link rel="stylesheet" href="/framework/css/style.css" type="text/css">
```

could it be the fact that I am developing locally on my machine using MAMP instead of on an actual web server?

**Comment by rdkempt** [comment]
If you right click the background and go "View page source", when you click on those links, do they load? It's a quick way to see if you're including them correctly, and also to see which URL it brings you to when you do click them (where it thinks they should be).

**Comment by agodlydeciple** [comment]
I think you're onto something. When I click the link for style.css it doesn't load it reverts back to the page but the url becomes:
http://localhost/bootstrap_template/**projects**/framework/css/style.css

it is looking in the /projects folder for the framework folder. So it does appear to be something path related.  

could it be something with the way I set the route up?

``` php
  Flight::route('*', array('Layout', 'buildLayout'));
```

**Comment by rdkempt** [comment]
What does your .htaccess file look like?

If you're using one that looks similar to this:

```
RewriteEngine On
RewriteBase /
RedirectMatch 301 ^(.+)/$ $1
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /index.php [L]
```

The rewrite condition states that if the requested URL does not point to a file it knows exists (for example, your CSS files), to forward the request to Flight. So, Flight should not be handling anything to do with your includes. It's a pathing issue, you need to specify the full absolute path to your CSS files. I don't know the folder structure you have setup, or if you're working in a subdirectory, etc... but that is the issue (or you need to fix your .htaccess file to include the rewrite condition).

**Comment by agodlydeciple** [comment]
here is my .htaccess:

> RewriteEngine On
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteCond %{REQUEST_FILENAME} !-d
> RewriteRule ^(.*)$ index.php [QSA,L]

here is my folder structure:
![image](https://cloud.githubusercontent.com/assets/683837/12626412/24dd0576-c4fe-11e5-83bc-1f993b01aa58.png)

**Comment by rdkempt** [comment]
Let me know if this works:

```
<link rel="stylesheet" href="/bootstrap_template/framework/css/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="/bootstrap_template/framework/css/bootstrap-theme.min.css" type="text/css">
<link rel="stylesheet" href="/bootstrap_template/framework/css/source-code-pro.css" type="text/css">
<link rel="stylesheet" href="/bootstrap_template/framework/css/style.css" type="text/css">
```

**Comment by agodlydeciple** [comment]
Yup that works!

**Comment by rdkempt** [comment]
So you're technically working out of a subdirectory. MAMP is running and looking at your root directory as whatever folder bootstrap_template is residing in. So the absolute path has to include the subdirectory you're running the project out of (bootstrap_template).

If you're only working on one project it might be easier to move it all up a directory outside of that bootstrap_template folder.

On any note, glad it's working for you - happy coding!

**Comment by agodlydeciple** [comment]
Yup that is exactly right - So i will need to figure out a way to create the subdir path and set it to a variable. Nonetheless, thank you again.
