### ISSUE TITLE
Php version compatability 

### ISSUE THREAD

**Issue by ghost** [flightphp/core#238]
This uses callable parameters which was introduced in php 5.4

**Comment by mikecao** [comment]
Callables have been around since PHP 4. You're thinking of type hinting, `function x(callable $c)`, which was introduced in PHP 5.4.

**Comment by ghost** [comment]
So in PHP 5.3 you can use callables but you can't hint at its type? Can you link me to some resources to demonstrate this. I am considering a few different PHP API Micro Frameworks (including Flight) and I am trying to run it on PHP 5.3, most of the others that have a callable parameter required 5.4

**Comment by jimlei** [comment]
@addui 

The PHP manual states

> Callbacks can be denoted by callable type hint as of PHP 5.4. This documentation used callback type information for the same purpose.

It also has multiple references to callables in earlier versions

> Static class methods can also be passed without instantiating an object of that class by passing the class name instead of an object at index 0. As of PHP 5.2.3, it is also possible to pass 'ClassName::methodName'.
> 
> Note: In PHP 4, it was necessary to use a reference to create a callback that points to the actual object, and not a copy of it. For more details, see References Explained.

http://php.net/manual/en/language.types.callable.php

---

You can easily try code in different versions of PHP using VMs (docker, virtualbox), or simple tests online ie here:

http://sandbox.onlinephpfunctions.com/
