### ISSUE TITLE
Object and named parameter

### ISSUE THREAD

**Issue by dooke** [flightphp/core#239]
Hi,

Is there a war to have named parameter when calling an object for a defined route ?

```
Flight::route('/api/@version/@name', array('MyApi', 'render'));
```

I want to retrieve : $version & $name

I can wrote this :

```
Flight::route('/api/@version/@name', function ($version, $name){
$a = new MyApi();
$a->render($version, $name);
});
```

But that's not what i want :(

Thx

**Comment by jimlei** [comment]
It should work with your class as well

``` php
Flight::route('/api/@version/@name', array('MyApi', 'render'));
```

``` php
class MyApi {
    public static function render($version, $name) {
      // Do awesome stuff
    }
}
```

**Comment by dooke** [comment]
Oh yeah sorry :) Thx 
I was trying with an extend of my object with same named function (with no parameter)
parent::render()

Thx
