### ISSUE TITLE
Get matching Route Pattern in before Method

### ISSUE THREAD

**Issue by micha-09** [flightphp/core#240]
Hi, 

i use this hook: `Flight::before('start', function($methods) {
    //GET, POST
    Flight::halt(403);
});` for testing.
It is possible to get the matched route in this method? For example get the Pattern of the matching route.

**Comment by mikecao** [comment]
No, routes are not matched until the framework starts.

**Comment by micha-09** [comment]
Ah ok is there another possibility to get the matched pattern before the callback is executed?

Cause, i want to check the access for this route before callback is executed.

**Comment by jimlei** [comment]
You _could_ of course use the router to find which route is the current, this will result in the router doing its work twice though

``` php
Flight::before('start', function() {
    // route the current request
    Flight::router()->route(Flight::request());
    // get the current route (false if no route is matched)
    $route = Flight::router()->current();
    if ($route) {
        // do something with the route
        // $route->pattern
    }
});
```

Another option could be to call some auth method on each route, downside is of course that you have to duplicate the calls throughout the routes. One upside is that it might be more readable / more clear which routes are protected..

``` php
<?php

require '../vendor/autoload.php';

Flight::map('denyAccessUnlessGranted', function($role) {
    // Get current user, ie from JWT or DB
    $user = new \stdClass();
    $user->roles = ['USER'];

    if (!in_array($role, $user->roles)) {
        Flight::halt(403);
    }
});

Flight::route('/', function(){
    echo 'hello world!';
});

Flight::route('/admin', function(){
    Flight::denyAccessUnlessGranted('ADMIN');
    echo 'Admins only!';
});

Flight::start();
```

**Comment by micha-09** [comment]
Wow, your first example is exactly what i need :) 

Big thanks :+1:
