### ISSUE TITLE
Flight::lastModified date format

### ISSUE THREAD

**Issue by susuper** [flightphp/core#241]
Hi.
`Flight::lastModified` function uses `date(DATE_RFC1123, $time)` to format date to be send in answer HTTP-headers.
Date will look like this: `Fri, 26 Feb 2016 09:20:27 +0000`
According to [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.3.1), dates should use "GMT" instead of "+0000".
I guess something like `gmdate('D, d M Y H:i:s \G\M\T', $time)` should be used to format date.

**Comment by mikecao** [comment]
Thanks for the PR.
