### ISSUE TITLE
 php7 error handling environmental issues arising

### ISSUE THREAD

**Issue by dux-web** [flightphp/core#242]
Fatal error: Uncaught TypeError: Argument 1 passed to flight\Engine::handleException() must be an instance of Exception, instance of Error given in /flight/Engine.php:153 Stack trace: #0 [internal function]: flight\Engine->handleException(Object(Error)) #1 {main} thrown in /flight/Engine.php on line 153

`public function handleException(\Exception $e) {`

Is replaced by the following normal

`public function handleException($e) {`

**Comment by jimlei** [comment]
@mikecao guess this makes #229 a bigger priority

**Comment by mikecao** [comment]
Fixed in f3fa0513fe2e1994923793b85c593b7f2b644001.
