### ISSUE TITLE
How can I call the php function in views?

### ISSUE THREAD

**Issue by LichFaker** [flightphp/core#244]

**Comment by mikecao** [comment]
Flight views are simply php scripts. You can call any PHP code in them.

**Comment by LichFaker** [comment]
In fact, I want to appoint the function in php to handle the html form. Otherwise, the html page will be jump to another and I know "ThinkPHP" can do it. Is Flight support?

**Comment by sabas** [comment]
If I understand your comment

``` php
Flight::route('GET /new', function () {
//call the view with the form
});
Flight::route('POST /new', function () {
// handle $_POST here
});
```

The action in the form

```
  <form method="POST" action="<?php echo Flight::request()->base.Flight::request()->url; ?>">
```

**Comment by LichFaker** [comment]
@sabas Thank you very much! It solved my problem
