### ISSUE TITLE
There is no sample application in flightphp

### ISSUE THREAD

**Issue by sudiptadeb** [flightphp/core#247]
@mikecao 
There is no sample application written in flight-php framework to give the developer a guideline to better coding practices using flight

I strongly suggest that a simple sample application which can show case the various features of flight-php along with the best way to structure the application will help developers to code better and efficient applications using this awesome framework

**Comment by jimlei** [comment]
I'm not sure, many micro frameworks don't really aim to solve the problem of writing an application - they just provide you with the foundation to build upon. Since every use case will be different and require different sets of building blocks on top of flight it's very hard to provide a sensible sample application.

**Comment by Conver** [comment]
I use Flight in many of my apps, in many different ways, with auth in front, as static site, as API controller.

We could add a sample/example folder to the repo, and add our own samples?
If you can provide an sample, submit it as a PR and it can be approved and added to the repo.

I'll be willing to submit different use cases.

What do you say @mikecao?

**Comment by mikecao** [comment]
@Conver I'd rather not include examples in the repo itself because I don't want people to think that is the standard way to setup their apps. I may go ahead and create a sample app, but it would definitely be a separate repo. I've seen lots of *-boilerplate repos that do the same thing.

**Comment by Conver** [comment]
@mikecao, that would also be a good way to goo', but I'll recommend letting users of Flight submit use cases of their own?

**Comment by mikecao** [comment]
@Conver Yes I think a variety of simple examples would be better than having a single complex sample.

**Comment by Conver** [comment]
@mikecao, Great. I'll love to submit some.

**Comment by Conver** [comment]
Let me know when you add the repo, and I'll push some.

**Comment by ycrao** [comment]
You can get some unofficial sample applications by searching [GitHub](https://github.com/search?&q=Flight%3A+An+extensible+micro-framework.&type=Code&utf8=%E2%9C%93) .
List some below:
https://github.com/olipayne/BcryptGenerator
https://github.com/itinnovator/myphp-app
https://github.com/casgin/LittleEducationalCMS
https://github.com/chiccomagnus/PGAPI
https://github.com/recepuncu/cms
https://github.com/ycrao/tinyme

**Comment by markhughes** [comment]
If anyone is looking for a good starting point I have forked a skeleton and brought it up to something more modern. It's pumped with some other things though (grunt + sass, twig)

https://github.com/markhughes/flight-skeleton

I plan to add a few things I need (like mongodb models) into it, but it is probably more than you would need already :)

**Comment by pierresh** [comment]
For those who might be interested with skeleton for a pure Restful API project, I have created one for that purpose: https://github.com/pierresh/flightphp-skeleton

**Comment by n0nag0n** [comment]
Added a few examples (that are still working) from this page. https://github.com/flightphp/core/commit/130deafab692a8111bbad7a8b926942258303944

**Comment by n0nag0n** [comment]
I just completed a skeleton app that might be helpful for those that find this issue. https://github.com/flightphp/skeleton
