### ISSUE TITLE
Problem with Bootstrap dropdown menu 

### ISSUE THREAD

**Issue by agodlydeciple** [flightphp/core#250]
First off - not sure if this is the right place for this but it is where I am going to at least start.

I am developing my site using the Flight framework and it seems to be working relatively well.  However, there seems to be a problem with the bootstrap dropdown menu in my nav bar. 

Basically what happens is when the site loads the dropdown works and I can access the contents and goto those specific pages.  However, when I am in one of the pages that is listed in the dropdown, when I click on the dropdown again - the options don't come up.

[https://sandbox.donoerkfitz.com](Here is a Link to my sandbox site) 

So if you are to click through all the options in the nav bar you'll see they all work, but if you click one of the 3 pages that are in the dropdown, it'll direct to it, but then the dropdown will stop working until you click one of the pages not in the dropdown then it'll start working again. 

Here is the dropdown working:
![image](https://cloud.githubusercontent.com/assets/683837/13887785/a896cd2c-ed0b-11e5-8ef4-700af1bb9c0c.png)

Any thoughts?

**Comment by jimlei** [comment]
This is not a Flight issue so it should be closed.

---

How are you including the sites assets (js, css, etc)?

On the front page you prepend every asset with `./`, which means from this dir

On the dropdown pages you prepend them with `../` which means from the dir above this one - but you've missed the bootstrap.js file!

Changing all of them to simply start with `/` will always load them from the website root - and should fix the issue

**Comment by agodlydeciple** [comment]
d'oh - you're right. I completely forgot the path for that. So as soon as I changed it, it worked. Thank you so much!
