### ISSUE TITLE
Add JSON response options

### ISSUE THREAD

**Issue by WoLfulus** [flightphp/core#255]
I found a case that I **need** to use JSON_UNESCAPED_UNICODE (integrating a system that the other end isn't mine and I can't fix the encoding).
I can't use Flight functions to do so since it doesn't provide a way to pass options to the json encoder.

Any possibilities to add this options, or even setting a "default options"?

Maybe something like:

```
Flight::set('flight.json.options', JSON_UNESCAPED_UNICODE);
```

**Comment by WoLfulus** [comment]
Oh, and for anyone with similar problems, I solved this by mapping (and using) a custom response method.

```
Flight::map('jsonc', function($obj, $status = 200) {
    Flight::response()
        ->status($status)
        ->header('Content-Type', 'application/javascript')
        ->write(utf8_decode(json_encode($obj, JSON_UNESCAPED_UNICODE)))
        ->send();
});
```

But I'd love to see this option on Flight ;)

**Comment by ghost** [comment]
@WoLfulus since the merging of https://github.com/mikecao/flight/pull/294, this feature is now available in dev-master. If you're happy with the fix, please close the issue - thanks for flagging it. 👍
