### ISSUE TITLE
Routes redirecting to 404 not found

### ISSUE THREAD

**Issue by agodlydeciple** [flightphp/core#257]
I have set up my routes, there are only two of them. / for home and /contact for the contact page. / works for home and I don't seem to have issues, but the moment I try to goto /contact it tells me the page can't be found.  

to specify my routes, I have a config value that is setup as such

``` php
$config['navPages'] = array(
    0 => array(
      "name" => "Home",
      "route" => "/"
    ),
    1 => array(
      "name" => "Contact",
      "route" => "/contact"
    ),
  );
```

then in my flight code I have this to define the routes:

``` php
Flight::map('generateRoutes', function($routes){
    require (Flight::get('view').'render.php');
    foreach($routes as $route){
      Flight::route($route['route'], array('Layout', 'buildLayout'));
    }
  });
```

And on index.php I have the command that is supposed to create the routes

``` php
  Flight::generateRoutes($config['navPages']);
```

all my code can be viewed on the dev branch of my repo at [https://git.oerkfitz.com/Websites/QuickPortfolio/](https://git.oerkfitz.com/Websites/QuickPortfolio/)

anyone have any thoughts as to what I could be doing wrong?

**Comment by agodlydeciple** [comment]
seemed to have been an issue with my development setup using MAMP.  Sorry about that.

**Comment by austin-codes** [comment]
Hey agodlydeciple, what was the issue with MAMP that you found?

**Comment by austinbenerdy** [comment]
**Note for future readers:** 
I ran across this issue when updating my MAMP install. By default there is an AllowOverride None in the httpd.conf file that you have to change prior to Flight PHP functioning properly. Took my way to long to figure out so hopefully I save you some pain.

**Comment by ar-anvd** [comment]
@austin-codes thanks, really helpful to me. 

This type of things should be available directly in docs. @mikecao
