### ISSUE TITLE
Regex-filtered named parameter value not passed to callback function when followed by optional named parameter

### ISSUE THREAD

**Issue by evansharp** [flightphp/core#259]
I'm reasonably sure this is a legitimate bug in routing . I've run out of ideas to test at any rate.

I'm working to specify a route in the following way:

``` php
Flight::route('/blog/@action:(\W|^)(write|edit|delete)(\W|$)(/@post_id:[0-9]+)', function($action, $post_id) {
      // do some stuff with a class here
 } );
```

While the routing occurs as expected\* and the callback function runs with no error, `$action` is never assigned.

\* - the URLs `../blog/write`, `../blog/edit`, and `../blog/delete` all trigger the callback. Any of these with an additional numeric segment also all work fine. The value of `$post_id` is always assigned correctly. 

I know that the easy work-around is to accept anything for `@action` and then do a switch in the function which defaults to the 404 route. But now that I've found this inconsistency, I want to know why!

What do you think?

**Comment by mikecao** [comment]
It's probably an issue with all the extra parentheses. Flight will take the given route and convert it into a regular expression, replacing certain parts. When the route regex is complicated, things can get messy. If you pass in `true` as a third parameter, you will get a `$route` variable in your callback which you can inspect.

``` php
Flight::route('/', function($route){
    // Array of HTTP methods matched against
    $route->methods;

    // Array of named parameters
    $route->params;

    // Matching regular expression
    $route->regex;

    // Contains the contents of any '*' used in the URL pattern
    $route->splat;
}, true);
```

You'll want to check out the `$route->regex` property.

**Comment by evansharp** [comment]
Thanks Mike, I'll have a look this weekend. I did try a few different ways of anchoring the regex initially (which did not use `(/W|^)` ) and none of them gave me the results expected. 

Glad this project is still going strong, I love my Flight-driven apps!

**Comment by evansharp** [comment]
More forms of this regex still arn't working. I've gone ahead a used a switch; it still _might_ be a bug.
