### ISSUE TITLE
How can I acces $_POST data?

### ISSUE THREAD

**Issue by simar88** [flightphp/core#260]
Hi everyone,
i'm having trouble on gettin the content of $_POST variable sent through ajax.
Can you give me some suggestions?
Thanks in advance.

**Comment by lkho** [comment]
http://flightphp.com/learn#requests

> You can access the query, data, cookies, and files properties as arrays or objects.

So, to get a POST variable, you can do:
`$id = Flight::request()->data['id'];`

**Comment by simar88** [comment]
Hi @lkho, i used all the methods but i was unable to access them.
After a lot of reviews on my code, I discovered that I wrote a wrong json reference in my request.
 It was just my fault! 
Thanks owever for your support! :)
