### ISSUE TITLE
Plugin for request and response object

### ISSUE THREAD

**Issue by Stephan123** [flightphp/core#262]
Hello,

i look for the best way to insert plugins to the flight framework.
I need plugins they works befor the controller work and after the controller has worked.

How can help ?

Your sincerly

Stephan

**Comment by jimlei** [comment]
You can use filtering to inject middleware into flight

> Flight allows you to filter methods before and after they are called. There are no predefined hooks you need to memorize. You can filter any of the default framework methods as well as any custom methods that you’ve mapped.

http://flightphp.com/learn#filtering
