### ISSUE TITLE
Seems that "noscript" blocks are causing improper rendering

### ISSUE THREAD

**Issue by paxperscientiam** [flightphp/core#263]
So, I'm not sure why this is happening, but it seems that "noscript" blocks are causing Flight to improperly render pages. That is, the "body" element loses its content whenever there is a "noscript" block present. This occurs even when the "notscript" block is empty.

**Comment by mentorkadriu** [comment]
Are you using twig to render pages ?

**Comment by mikecao** [comment]
That shouldn't be possible. Try saving the output to an html file then loading that and see if you still get the same issue.

**Comment by paxperscientiam** [comment]
@mentorkadriu No, just straight Flight.

@mikecao Sorry, it seems I was mistaken: the error seems to stem from the javascript library "InstantClick".
