### ISSUE TITLE
Create Json using Flight php

### ISSUE THREAD

**Issue by Auron691** [flightphp/core#269]
I have a problem where I have to create a JSON using Flight::json. I have an array, called $data, that contains some elements like

`$data[] = array('id'=>$temp,'type'=>'remote','url'=>$path);`
where $id and $path have different values like this:

`[id] => http://desktop-pqb3a65:8080/marmotta/resource/22086372-476f-4974-b538-64019ab678b3
[url] => D:\Software\Marmotta\marmotta-home\resources\1d\4d\ea\1d4dea13-f8e6-4cf0-b96a-f88b08efda2b`
When I try to convert that in a JSON using:

`Flight::json($data);`
my PHP page returns me this format instead:

`{"id":"http:\/\/desktop-pqb3a65:8080\/marmotta\/resource\/22086372-476f-4974-b538-64019ab678b3","type":"remote","url":"D:\\Software\\Marmotta\\marmotta-home\\resources\\1d\\4d\\ea\\1d4dea13-f8e6-4cf0-b96a-f88b08efda2b"}`
I read the documentation and I tried to convert using another function:

`Flight::json($data, $code = 200, $encode = false, $charset = 'utf-8');`
but it return an error like:

`500 Internal Server Error
Array to string conversion (8)`
So can you help me to convert $data without this type of error? 
Thanks for help

**Comment by jimlei** [comment]
This is valid json:

```
{
    "id": "http:\/\/desktop-pqb3a65:8080\/marmotta\/resource\/22086372-476f-4974-b538-64019ab678b3",
    "type": "remote",
    "url": "D:\\Software\\Marmotta\\marmotta-home\\resources\\1d\\4d\\ea\\1d4dea13-f8e6-4cf0-b96a-f88b08efda2b"
}
```

The slashes are escaped in JSON output, it will be corrected/unescaped wherever you decode the json.

> A string is a sequence of zero or more Unicode characters, wrapped in double quotes, using backslash escapes. A character is represented as a single character string. A string is very much like a C or Java string.
> 
> Any UNICODE character except " or \ or control character

http://www.json.org/
