### ISSUE TITLE
Named Parameters Using RegEx not working?

### ISSUE THREAD

**Issue by ghost** [flightphp/core#277]
Hey, I really enjoy this framework and I think its a really nifty tool for building applications. But I have encountered an issue. Take a look, this just redirects to my 404 page 

![](https://i.gyazo.com/d04f672ab3717225b7125cde16389799.png)

**Comment by mikecao** [comment]
What url are you testing?

**Comment by ghost** [comment]
http://localhost/54vg

**Comment by mikecao** [comment]
Your regex is wrong. It's checking if the url is [a-z] OR [0-9] OR [A-Z]. If you just want to allow alpha-numeric, all you need is [\w]+.

**Comment by ghost** [comment]
Thanks. I checked it on two RegEx sites and it checked out. But its cool, thanks again man. Great work

**Comment by lin-credible** [comment]
I also have a problem about the route. I write a RE like "**(foo|bar)**". So, I changed the Route.php, Route->`matchUrl()` function:
`'#@([\w]+)(:([^/\(\)]*))?#'`,  //original
`'#@([\w]+)(:([^/]*))?#'`,  //now
-->So, I can match the Regular Expression. 😄 Any problems?? @mikecao

**Comment by mikecao** [comment]
@lin-credible The reason it doesn't match parentheses `()` is because complicated regular expressions, with lots of nested matching groups would not match correctly.
