### ISSUE TITLE
Routing prefix

### ISSUE THREAD

**Issue by artyuum** [flightphp/core#281]
Hi, 
I really like Flight, thanks for your work.
How can I add a routing prefix in every URLs ?
For example, here is the prefix I want to add in the URLs : /api/v1
I would like to know if there is a way to do that without manually edit every routes in my code just to add "/api/v1/".

**Comment by mikecao** [comment]
It would need to be an enhancement. I can probably do it as part of #276.

**Comment by n0nag0n** [comment]
I just added this feature in https://github.com/flightphp/core/tree/route-grouping Let me know if this is what you were looking for.

**Comment by krmu** [comment]
@n0nag0n this is fixed I guess.
