### ISSUE TITLE
Route problem - end slash in route

### ISSUE THREAD

**Issue by andrey900** [flightphp/core#283]
Why if get "/users" use action for route "/users/" ?

**Comment by mikecao** [comment]
By default, Flight considers routes with and without the ending slash to be the same. Maybe I can make it configurable.

**Comment by andrey900** [comment]
It would be good, it is all the same 2 different URL. If it is solved please make. Thanks!

**Comment by andrey900** [comment]
yes, i'm find another problem)))
for route pattern: /serials/@code[\w]+/
get url: /serials/voyna_i_mir_war_peace_2016_/
code variable in method: voyna_i_mir_war_peace_2016
Why missing the last character "_"?

**Comment by mikecao** [comment]
Your route is wrong. It should be `/serials/@code:[\w]+/`.
