### ISSUE TITLE
Routing always matches GET regardles of form method, in specific situation

### ISSUE THREAD

**Issue by nprasovic** [flightphp/core#284]
I have this in my httpd.conf:

```
Alias /api "/path/to/backend/"
```

So my REST API is accessible via both "/api" and "/api/" URLs.

This is test html:

```
<form action="/api" method="post">
<input type="text" name="bla_input"/>
<input type="submit" value="Submit POST"/>
</form>

<form action="/api" method="get">
<input type="text" name="bla_input"/>
<input type="submit" value="Submit GET"/>
</form>
```

This is .htaccess:

```
RewriteEngine On
RewriteBase /api/ # notice that this can also be /api with same results
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]
```

This is test index.php under "/api"

```
<?php
echo '_POST<br>';
print_r($_POST);

require __DIR__ . '/vendor/autoload.php';

Flight::route('GET /', function(){
    echo 'I received a GET request.';
    $request = Flight::request();
    echo $request->method;
});

Flight::route('POST /', function(){
    echo 'I received a POST request.';
    $request = Flight::request();
    echo $request->method;
});

Flight::start();
```

Now:

1.) **bug??** If form action is "/api", route will only match 'GET /' no matter if form has method "post" or "get". In Apache access log I can see that browser correctly submits POST and GET requests respectively.

2.) if form action is "/api/" (with trailing slash) then routes are correctly matched: 'GET /' for GET form method and 'POST /' for POST form method.

If I set alias in Apache like this:

```
Alias /api/ "/path/to/backend/"
```

I then won't be able to use "/api" URL (Apache will return 404) so above issue never manifests.

I don't know if this is a bug or feature, but it has cost me quite a bit of time to figure it out so I thought I might post it here to either be fixed (if it's a bug) or to help someone who encounters the same issue.

**Comment by magnus-eriksson** [comment]
Isn't this because your rules & set up actually redirects calls for `/api` to `/api/` (in Apache and your rewrite rules, that is)? All redirects are always done with GET.

Paths with and without trailing slashes aren't considered to be the same resource. 

When building an API, you should decide on one or the other. There are lengthy articles and discussions out there about when you should use which.
