### ISSUE TITLE
Unable to pass variables as parameters in array argument on Flight::register()

### ISSUE THREAD

**Issue by loftyD** [flightphp/core#285]
Hello!

I have a bit of an issue, I have a function which I have registered:
`
Flight::register("fieldManager","FieldManager",array("app_users",NULL) );
`
Is there a way where I can pass through a variable into the array, which then is sent to the constructor of the class?

For example: `Flight::fieldManager("a)";` or `Flight::fieldManager("b");`

If you could let me know then that would be fab!

Thanks

Ben

**Comment by tamtamchik** [comment]
You mapped a class, not a method, that's why Flight returns you it as a shared instance.
If you want to make some kind of factory for your `FieldManager` use `map` method. It's a function mapping, and there you can do something like this:

``` php
// Map your method
Flight::map('fieldManager', function($param){
    return new FieldManager(["app_users", $param, NULL]);
});

// this will be passed to constructor
Flight::fieldManager("a)";
```

**Comment by loftyD** [comment]
Hello!

Thank you so much for your help :)

I will close this issue.
