### ISSUE TITLE
Is this PSR-4 Autoload compatible ?

### ISSUE THREAD

**Issue by itinnovator** [flightphp/core#287]
we were trying to integrate routing system into our small php system to test the routing performance. However, we found it really hard to load classes with namespace. 

Those namespace was defined and auto-loaded as per PSR-4.

Finally, we achieved class loading by custom code in route.php. Is there any plan to make it PSR-4 compatible ? 

Thank you

**Comment by mikecao** [comment]
Are you trying to load custom classes into Flight or loading Flight classes into your app?

**Comment by itinnovator** [comment]
I am trying to load Flight Classes into my app. 

Though, i got ride of this situation, but because you're the developer and read every code of this beautiful app i though i can talk with you regarding this. 

Thanks.

**Comment by mikecao** [comment]
The classes are all in standard folders so your autoloading function should be able to load them. So `use \flight\net\Router` would refer to the file in `flight\net\Router.php`.
