### ISSUE TITLE
Does this support XML(not an issue actually)

### ISSUE THREAD

**Issue by dingzhanjun** [flightphp/core#288]
I want to use flight with XML, this is not an issue, but there is no where I can add comments.

Thanks

**Comment by mikecao** [comment]
Yes, you can send anything as a response. You just need to set the right headers, which I believe is `application/xml`.

**Comment by dingzhanjun** [comment]
I tried send XML to flight, it does not get anything, I guess I need to fork this to make it support XML for both request and response.

**Comment by mikecao** [comment]
Flight just uses whatever the web server sends over. It can be post data, json, xml, files, raw data, anything that the web server accepts. It's not a Flight issue. How are you trying to get the data?

**Comment by dingzhanjun** [comment]
Thanks for your response!

Here is the xml I posted to server:     <Echo>12345</Echo>

Here is code on server end which map a path named "Ping":
Flight::route('POST /Ping', function() use ($hotelModel, $security){
    echo Flight::json(Flight::request()->data->Echo);  //for testing, XML is not parsed into data 
      //I under stand I need to format the data into XML based on client accept header, I cannot even have the incoming xml

```
try {
    if ($hotelModel->checkSecurity($security)) {
        $echo =  $hotelModel->Ping(Flight::request()->data->Echo);

        if(isset($echo["Error"])){
            $response = array(
                'Status' => "Fail",
                "Echo" => $echo
            );
        } else {
            $response = array(
                'Status' => "Success",
                "Echo" => $echo
            );
        }
        echo Flight::json($response);
    } else {
        Flight::response()->header("Status", "Fail");
        Flight::response()->header("ErrorCode", "InvalidAuthentication");
        Flight::response()->header("ErrorMessage", "Invalid username or password");
        Flight::halt(401, 'NotAuthorized');
    }
} catch (Exception $e) {
    Flight::response()->header("Status", "Fail");
    Flight::response()->header("ErrorCode", $e->getCode());
    Flight::response()->header("ErrorMessage", $e->getMessage());
    Flight::halt(500, 'ServerError');
}
```

});

**Comment by mikecao** [comment]
Do a `var_dump($_POST)`. That should show you what PHP is getting from the server. Flight gets the values from there.
