### ISSUE TITLE
Can json_encode options to be set?

### ISSUE THREAD

**Issue by wwtg99** [flightphp/core#290]
In the `Flight::json()` function, options of json_encode can not be set such as `JSON_UNESCAPED_UNICODE`,

```
public function _json($data, $code = 200, $encode = true, $charset = 'utf-8') {
        $json = ($encode) ? json_encode($data, JSON_UNESCAPED_UNICODE) : $data;
        $this->response()
            ->status($code)
            ->header('Content-Type', 'application/json; charset='.$charset)
            ->write($json)
            ->send();
}
```

Can this option be set manually by passing parameters or load from config?
Thank you!

**Comment by ghost** [comment]
@wwtg99 This enhancement has been merged, are you happy with the change?
