### ISSUE TITLE
save text with apostrophe on MYSQL with flight

### ISSUE THREAD

**Issue by simar88** [flightphp/core#291]
Hello everyone!
I can't save text with apostrophe inside mysql DB. In the traditional way I often use **utf-8 encoding** combined with **mysql_real_escape_string** but this is the first time that i've to do with flight.
Can you help me?
Thanks in advance,
Simone

**Comment by simar88** [comment]
solved!
I've to use addslashes()
Bye :)

**Comment by jimlei** [comment]
@simar88 this is unrelated to flight but I wanted to mention it.

> The mysql extension for PHP is incredibly old and has superseded by two other extensions:
> mysqli
> pdo
> 
> Not only did development stop long ago on mysql, but it was deprecated as of PHP 5.5.0, and has been > officially removed in PHP 7.0.

In addition to the deprecation/removal, the mysql extension does not offer any proper solution to SQL injection hacks.

A mysql example converted to PDO could look like this

``` php
<?php
$pdo = new PDO('sqlite:/path/db/users.db');
$pdo->query("SELECT name FROM users WHERE id = " . $_GET['id']);
```

This is still vulnerable to SQL injection, where a malicious user could insert code into $_GET['id'] which will then be evaluated by your database backend. It really doesn't even have to be malicious, as you've experiences with adding a single quote that breaks the query.

PDO fixes this issue by allowing you to pass the query string and the variables/parameters separate to the database backend. That way your mysql server knows it should not execute whatever data the users have passed in through your get variables or forms.

``` php
<?php
$pdo = new PDO('sqlite:/path/db/users.db');
$pdo->prepare("SELECT name FROM users WHERE id = ?");
$pdo->execute([$_GET['id']]);
```

Read more
http://www.phptherightway.com/

**Comment by simar88** [comment]
@jimlei thanks for you reply.
Can you anyway suggest me the best practices tu save and get text with chars like **é à ò** and so on? What is the best solution to have them saved in database with PDO and to use them in client with javascript for example?
Is the first time that i use flight php and some things are little bit different compared to some practices that i used before.
Thank in advance,
Simone

**Comment by ghost** [comment]
@simar88 Hi, just in case you haven't yet figured out how to transport unicode characters between your application and your database, you can use the following command:

`$pdo->setAttribute(PDO::MYSQL_ATTR_INIT_COMMAND, "SET NAMES 'utf8'");`

You should use this directly after your `new PDO` class instantiation.

It's probably worth giving this blog post by Joel Spolsky a read: http://www.joelonsoftware.com/articles/Unicode.html (The Absolute Minimum Every Software Developer Absolutely, Positively Must Know About Unicode and Character Sets)
