### ISSUE TITLE
All Non-Root Pages 404 If Not Root Directory?

### ISSUE THREAD

**Issue by Jeremy1026** [flightphp/core#292]
I have my page installed on my server at /page/flight/index.php which can be accessed at www.example.com/flight/. Here only the homepage works, if I try to use any of the routes defined in route.php such as www.example.com/flight/hello it will return a 404. Is there something I need to set to tell flight to expect things to not be the root of the domain?

**Comment by mikecao** [comment]
Is the 404 coming from Flight or the web server?

You can try setting the config value `flight.base_url`, which will tell Flight which sub directory it's under.

**Comment by Jeremy1026** [comment]
Not sure how to determine which the 404 is coming from? I can see it in my server's error log.

**Comment by mikecao** [comment]
Flight's standard 404 page looks like this:

```
404 Not Found

The page you have requested could not be found.
```

You can also override the `notFound` method to display your own message. The idea is that if the error is coming from Flight, then at least you have it configured correctly and you can use `flight.base_url`. If it's coming from the webserver, then you need to fix your rewrite rules on the server.

**Comment by Jeremy1026** [comment]
And closing. I'm dumb, I didn't do the .htaccess updates.
