### ISSUE TITLE
flight call exit() after send response

### ISSUE THREAD

**Issue by xdudi** [flightphp/core#297]
In my implementation I need to make cleanup after send a response. If flight call a exit(), php calls my objects' destructors in wrong order, and it makes a lot of problems.

It would be nice to have although option in config to disable it if that behaviour should stay.

[Toxic line](https://github.com/mikecao/flight/blob/afbf306336959cf8476911835de3510ca7542644/flight/net/Response.php#L269).

**Comment by mikecao** [comment]
I think this will require a major update to how requests/reponses are handled, but it's something I've been meaning to work on for a while.

**Comment by leeoniya** [comment]
another use case is to do after-response lazy logging

**Comment by mikecao** [comment]
Fixed in  7ae2011723042037e2d7334cc295843febed340b. Sending a response now no longer calls exit. You can now apply filters via `Flight::before('stop', ...)`.
