### ISSUE TITLE
Avoid permanent overwrite in template vars

### ISSUE THREAD

**Issue by pgoforth** [flightphp/core#299]
In working with Flight, I have found many times that If I render the same template consecutively, they will inherit the values from the previously rendered template unless I redefine them in the subsequent render calls. If I am checking if a variable isset(), I can get the wrong value if I passed the variable in a previous render call.
```PHP
// name_template.php
<h1>Hello my name is <?php echo isset($name) ? $name : 'Noname'; ?></h1>
```
```PHP
// home.php
<?php
echo $name_1;
echo $name_2;
?>
```
Then rendering consecutively:
```PHP
Flight::render('name_template.php', array( 'name' => 'Bill' ), 'name_1');
Flight::render('name_template.php', array(), 'name_2');
Flight::render('home.php', array());
```
Would make:
```HTML
<h1>Hello my name is Bill</h1>
<h1>Hello my name is Bill</h1>
```
This could be solved by modifying the render method slightly, to revert the 'vars' back to their original state after the render:
```PHP
public function render($file, $data = null) {
        $this->template = $this->getTemplate($file);

        if (!file_exists($this->template)) {
            throw new \Exception("Template file not found: {$this->template}.");
        }

        if (is_array($data)) {
            $old_vars = $this->vars;
            $this->vars = array_merge($this->vars, $data);
        }

        extract($this->vars);

        include $this->template;

        if (is_array($data)) {
            $this->vars = $old_vars;
        }

    }
```
This would allow 'nested' calls to render to inherit data, but not subsequent calls.

Perhaps it could be done with a flag as well, but I think that's unnecessary. I'd be curious to hear reasons why you would want to permit the passed $data parameters for one template to be available to subsequent templates without implicitly setting them using:
```PHP
Flight::view()->set()
```

**Comment by mikecao** [comment]
The reason variables are passed on is to support layouts. So you would first render all your partials:

```
Flight::render('header', array(), 'header_content');
Flight::render('footer', array(), 'footer_content');
```

And then have those variables `$header_content` and `$footer_content` available in the next render call.

```
Flight::render('layout', array());
```

But you're right it probably shouldn't pollute the variable space. This can be solved by always explicitly sending over values you expect in your template. So in your example you would pass `array('name' => null)`.
