### ISSUE TITLE
Compatibility question on mac

### ISSUE THREAD

**Issue by ycrao** [flightphp/core#302]
It get some errors when  I using flight on Mac and make me confused.
But it does work on Windows and Linux.
You can get code from https://github.com/ycrao/tinyme .

In `app\route.php`, when I using 

```
    Flight::route('GET /', ['HomeController', 'index']);
```

It will get `The use statement with non-compound name 'Flight' has no effect` error.

![image](https://cloud.githubusercontent.com/assets/3280204/20613654/febbdd58-b300-11e6-80c0-cbad1af9ed58.png)

After I change it like below:

```
    Flight::route('GET /', ['//HomeController', 'index']);
```
It will get `Invalid callback specified.` error.

![image](https://cloud.githubusercontent.com/assets/3280204/20613651/e96ea6e2-b300-11e6-92a5-3e5932c63f1d.png)

using `Flight::path()` to load controller class. 

Here is my environment:

```bash
➜  ~ php -v
PHP 5.6.25 (cli) (built: Sep 19 2016 15:45:41)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
~ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
hash
iconv
json
ldap
libxml
mbstring
mcrypt
mysql
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

[Zend Modules]
➜  ~ nginx -v
nginx version: nginx/1.10.2

➜  ~ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.1 (16B2657)
      Kernel Version: Darwin 16.1.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ***MacBook Pro
      User Name: ***
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1:24
```

**Comment by mikecao** [comment]
Do you have the statment `use Flight` somewhere in your code? That is what the error is complaining about. When you changed your code to `//HomeController`, that shouldn't work because namespaces use backslash `\`.

**Comment by ycrao** [comment]
@mikecao Thanks a lot.
I have removed all `use` statement at the beginning of controller files. It get fine.
I guess when using `Flight::path()` by requiring files to load class , you no need to `use` these namespace-less-classes.
