### ISSUE TITLE
Can't render '.html' files. 

### ISSUE THREAD

**Issue by guilhermevini** [flightphp/core#305]
I need to render a single html file, but the Fight core fixed the php extension.

**flight\flight\template\view.php**

```
    /**
     * Gets the full path to a template file.
     *
     * @param string $file Template file
     * @return string Template file location
     */
    public function getTemplate($file) {
        if ((substr($file, -4) != '.php')) {
            $file .= '.php';
        }
        return $this->path.'/'.$file;
    }
```

**Comment by jimlei** [comment]
I think it's useful that it automatically changes ie 'contact' to 'contact.php'. Even if it's only HTML in your template it's perfectly fine to use .php

**Comment by mikecao** [comment]
@guilhermevini Looks like you are on an older version. Later versions allow you to configure the extension with a setting.

`flight.views.extension - View template file extension. (default: .php)`
