### ISSUE TITLE
Filtering route fires 3 times

### ISSUE THREAD

**Issue by NicoGrapsas** [flightphp/core#308]
Hi
I wanna implement some middleware on routes (for authentication)

The following code fires 3 times for each request

```
$app->before('route`, function(&$param, &$output) {
 echo 'something';
});

```

Is this expected behavior? 
It worries me about performance

**Comment by mikecao** [comment]
The `route` method adds routes to the registry. It doesn't do the actual routing. What you want is to do `$app->before('start', ...)` or map your own method and filter that:

```php
$app->map('handleRoute', ...);

$app->before('handleRoute', ...);

$app->route('/', function(){
  $app->handleRoute();
});
```

**Comment by NicoGrapsas** [comment]
I know route doesn't do routing but... when a request comes in the event fires anyway. Why ?

The problem with your approach is that i need to protect all routes with authentication. Isn't practical.

**Comment by NicoGrapsas** [comment]
Using wildcard and returning true does the trick

```
$app->route('/*', function(){
  global $app;
  var_dump($app->request()->url);
  //check if user is authenticated or redirect to login
  return true;
});
```

**Comment by mikecao** [comment]
When you do `$app->before('route', ...)` that means the filter will be called every time the route method is called. So if you declare 3 routes, it will be called 3 times. So you shouldn't be filtering route at all.
