### ISSUE TITLE
Class 'Flight' not found in form submit script

### ISSUE THREAD

**Issue by agodlydeciple** [flightphp/core#311]
Trying to execute a submit script from a form. But when I call on of my defined methods, it gives me the following error:
_**Fatal error**: Class 'Flight' not found in **script_file.php** on line **4**_

my Script looks like this:
```php
<?php
  session_start();

  $db = Flight::db();

  $records = $_SESSION['records'];

  define('URL_BASE', "http://www.omdbapi.com/?");
  // $url_base = "http://www.omdbapi.com/?t=21+jump+street&y=&plot=full&r=json";

  if(!empty($_POST['checkbox'])) {
      $curl = curl_init();
      // Disable SSL verification
      curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
      // Will return the response, if false it print the response
      curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
      foreach($_POST['checkbox'] as $checkValue) {
        $url = URL_BASE . "t=" . str_replace(" ", "+", $records[$checkValue]['Name']);
        if($records[$checkValue]['Year'] == ""){ $url .= "&y="; }
        else{ $url .= "&y=" . $records[$checkValue]['Year']; }

        $url .= "&plot=full&r=json";

        curl_setopt($curl, CURLOPT_URL, $url);
        // Execute
        $result=curl_exec($curl);

        $data = json_decode($result, true);

        Flight::storedProcedure('insert_into_movie_data', array($checkValue, $data['Title'], $data['Released'], $data['Genre'], $data['Plot'], $data['Poster']));
      }
      //> close curl_init
      curl_close($curl);
  }
  else { echo "Nothing Selected"; }
?>
```

What am I missing here?

**Comment by shaneshuford** [comment]
`require_once('Flight.php');`
?

**Comment by agodlydeciple** [comment]
I have that in my main script.  

Re-requiring the Flight.php script means I have to re-require all of my Flight variables and re-initialize all my Flight methods in order to use them.  That doesn't seem right. 

Any other thoughts?

**Comment by jimlei** [comment]
You need to include your main script then.

**Comment by shaneshuford** [comment]
I don't think it's possible to answer this question without more information.
Your error message is simply saying that Flight doesn't exist. which means it was not created.

`print_r(get_declared_classes());`

**Comment by agodlydeciple** [comment]
@jimlei - include my index.php? that doesn't seem right either.

@shaneshuford here is my print_r(get_declared_classes()) output:
```Array ( [0] => stdClass [1] => Exception [2] => ErrorException [3] => Closure [4] => Generator [5] => DateTime [6] => DateTimeImmutable [7] => DateTimeZone [8] => DateInterval [9] => DatePeriod [10] => LogicException [11] => BadFunctionCallException [12] => BadMethodCallException [13] => DomainException [14] => InvalidArgumentException [15] => LengthException [16] => OutOfRangeException [17] => RuntimeException [18] => OutOfBoundsException [19] => OverflowException [20] => RangeException [21] => UnderflowException [22] => UnexpectedValueException [23] => RecursiveIteratorIterator [24] => IteratorIterator [25] => FilterIterator [26] => RecursiveFilterIterator [27] => CallbackFilterIterator [28] => RecursiveCallbackFilterIterator [29] => ParentIterator [30] => LimitIterator [31] => CachingIterator [32] => RecursiveCachingIterator [33] => NoRewindIterator [34] => AppendIterator [35] => InfiniteIterator [36] => RegexIterator [37] => RecursiveRegexIterator [38] => EmptyIterator [39] => RecursiveTreeIterator [40] => ArrayObject [41] => ArrayIterator [42] => RecursiveArrayIterator [43] => SplFileInfo [44] => DirectoryIterator [45] => FilesystemIterator [46] => RecursiveDirectoryIterator [47] => GlobIterator [48] => SplFileObject [49] => SplTempFileObject [50] => SplDoublyLinkedList [51] => SplQueue [52] => SplStack [53] => SplHeap [54] => SplMinHeap [55] => SplMaxHeap [56] => SplPriorityQueue [57] => SplFixedArray [58] => SplObjectStorage [59] => MultipleIterator [60] => ReflectionException [61] => Reflection [62] => ReflectionFunctionAbstract [63] => ReflectionFunction [64] => ReflectionParameter [65] => ReflectionMethod [66] => ReflectionClass [67] => ReflectionObject [68] => ReflectionProperty [69] => ReflectionExtension [70] => ReflectionZendExtension [71] => SessionHandler [72] => __PHP_Incomplete_Class [73] => php_user_filter [74] => Directory [75] => ZipArchive [76] => LibXMLError [77] => DOMException [78] => DOMStringList [79] => DOMNameList [80] => DOMImplementationList [81] => DOMImplementationSource [82] => DOMImplementation [83] => DOMNode [84] => DOMNameSpaceNode [85] => DOMDocumentFragment [86] => DOMDocument [87] => DOMNodeList [88] => DOMNamedNodeMap [89] => DOMCharacterData [90] => DOMAttr [91] => DOMElement [92] => DOMText [93] => DOMComment [94] => DOMTypeinfo [95] => DOMUserDataHandler [96] => DOMDomError [97] => DOMErrorHandler [98] => DOMLocator [99] => DOMConfiguration [100] => DOMCdataSection [101] => DOMDocumentType [102] => DOMNotation [103] => DOMEntity [104] => DOMEntityReference [105] => DOMProcessingInstruction [106] => DOMStringExtend [107] => DOMXPath [108] => PDOException [109] => PDO [110] => PDOStatement [111] => PDORow [112] => SimpleXMLElement [113] => SimpleXMLIterator [114] => XMLReader [115] => XMLWriter [116] => CURLFile [117] => finfo [118] => mysqli_sql_exception [119] => mysqli_driver [120] => mysqli [121] => mysqli_warning [122] => mysqli_result [123] => mysqli_stmt [124] => PharException [125] => Phar [126] => PharData [127] => PharFileInfo ) ```

**Comment by tamtamchik** [comment]
You do load neither `flight` nor any other `scripts` in your snippet.
Because interpreter does not know what the `flight` is it gives you a fatal error :) 

> Re-requiring the Flight.php script means I have to re-require all of my Flight variables and re-initialize all my Flight methods in order to use them. That doesn't seem right.

That seemed exactly right. In order to be consistent, your "framework" should be initialized in the same manner among all your scripts, this will make it usable. If you have to write all files differently this is something that does not seem right.

Try to separate "framework" initialization from representation at least into separate file first (call it bootstrap.php for example), and include this initialization in all your scripts.

Divide & conquer :)

**Comment by agodlydeciple** [comment]
@tamtamchik thank you for your response.  It does appear by initializing my script in the same manner as I do the root of my app works!  

Thanks, everyone! Sorry for my issues!
