### ISSUE TITLE
Can't have multiple routing parameters without slashes in between?

### ISSUE THREAD

**Issue by arcataroger** [flightphp/core#312]
Trying to do a route like:

```
Flight::route('/get-image/@id:\d{7}.@format:.{3}', function ($id, $format) {
getImage($id, $format);
});
```

It's the regex/parameter separation that doesn't seem to work:
`@id:\d{7}.@format:.{3}`

This works:
`@id:\d{7}/@format:.{3}` (with a slash instead of period in between)

This also works:
`@id:\d{7}.(@format:.{3})` (as a side effect of wrapping the second parameter in parentheses)

But ultimately I was hoping for a route that could do imagename.filetype like imagename.png or imagename.jpg and pass that as a second parameter, instead of imagename/png or imagename/jpg.

I believe this is a bug? The documentation wasn't clear about how to separate one regex parameter from another and slash seems to be the magical character.

**Comment by mikecao** [comment]
The officially supported way is to only work on URL segments. Something like  `/@id1:<regex>/@id2:<regex>`. What happens behind the scenes is the route definition gets compiled into a single large regex. When you start introducing parentheses, you're introducing some side-effects into the final regex. But if it works, then just go with it.
