### ISSUE TITLE
Absolute url difference between root and subfolder

### ISSUE THREAD

**Issue by sabas** [flightphp/core#313]
I usually make my absolute urls like
```php
echo Flight::request()->base."/route/1";
```
When installing it in a subfolder works correctly (I don't even set RewriteBase in the htaccess)
But when I move the application to the root folder, the resulting url has 2 slashes, so I have to change the code like
```php
echo Flight::request()->base."route/1";
```
In the form action normally I use (and it works) ```Flight::request()->base.Flight::request(()->url```.

Am I doing something wrong?
Could be similar to #193

**Comment by ghost** [comment]
Seems like `Flight::request()->base` does not have a trailing slash when flight framework is installed in a subdirectory.

**Comment by krmu** [comment]
#193
