### ISSUE TITLE
Setting content-type to image/png doesn't display image

### ISSUE THREAD

**Issue by jmuraca** [flightphp/core#315]
I am trying to create a route which generates and image using PHP's GD library and serves it to the user. I think there is a clash between Flight and setting the image content type header

```
Flight::route('GET /share/', function()
{    
    $image = imagecreatetruecolor(400, 400);
    $white = imagecolorallocate($image, 255, 255, 255);
    $black = imagecolorallocate($image, 68, 68, 68);
    imagefill($image, 0, 0, $white);

    imagettftext($image, 12, 0, 20, 200, $black, DIR_FONTS."arial.ttf", "TEST IMAGE"); 
    header("Content-Type: image/png");
    imagepng($image);
});
```

The enclosed code works in a standalone php file but when I put it inside a Flight route, it returns 200 OK but the image is not presented.

**Comment by mikecao** [comment]
Are you getting anything in the body of the response? Flight uses output buffering, so there may be a conflict with how `imagepng` works. More info here, http://stackoverflow.com/questions/19527455/php-how-to-solve-ob-start-in-combination-imagepng-issue

You can also try creating your own response and see if that works:

```
Flight::route('GET /share/', function()
{  
    // Generate image data
    $imageData = ...

    // Send response
    $this->response(false)
        ->status($code)
        ->header('Content-Type', 'image/png')
        ->write($imageData)
        ->send();
});
```
