### ISSUE TITLE
When are we having php7 support?

### ISSUE THREAD

**Issue by vishtany** [flightphp/core#316]
i had an error while migrating from a php5.6 local server to a local server with php7, during a previous login script using POST data where i then received the following error on my 505 page: 
` #0 C:\xampp\htdocs\bvapp\vendor\mikecao\flight\flight\core\Dispatcher.php(165): {closure}()
#1 C:\xampp\htdocs\bvapp\vendor\mikecao\flight\flight\core\Dispatcher.php(143): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#2 C:\xampp\htdocs\bvapp\vendor\mikecao\flight\flight\Engine.php(322): flight\core\Dispatcher::execute(Object(Closure), Array)
#3 C:\xampp\htdocs\bvapp\vendor\mikecao\flight\flight\core\Dispatcher.php(196): flight\Engine->_start()
#4 C:\xampp\htdocs\bvapp\vendor\mikecao\flight\flight\core\Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#5 C:\xampp\htdocs\bvapp\vendor\mikecao\flight\flight\core\Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#6 C:\xampp\htdocs\bvapp\vendor\mikecao\flight\flight\Engine.php(65): flight\core\Dispatcher->run('start', Array)
#7 C:\xampp\htdocs\bvapp\vendor\mikecao\flight\flight\core\Dispatcher.php(196): flight\Engine->__call('start', Array)
#8 C:\xampp\htdocs\bvapp\vendor\mikecao\flight\flight\Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array)
#9 C:\xampp\htdocs\bvapp\index.php(49): Flight::__callStatic('start', Array)
#10 {main}  `
went to here trying to solve an issue which has since been fixed based on other pull requests here => [PHP7 Migration Incompatibility ](https://secure.php.net/manual/en/migration70.incompatible.php)

[Screenshot](http://prntscr.com/eiwmmt)

**Comment by mikecao** [comment]
What is the actual error? Flight should work fine in PHP 7.

**Comment by vishtany** [comment]
i am here still getting that error message hence i am not sure what is the issue. The last line referenced in the error list (tree) is related to `Flight::start();`
Sorry for the subject line since i did'nt find other tickets earlier during my search but now Looking at the change-log,  i can see there is support but i am wondering why this error? 
I will try to do a 7.1.1 update to my local server or downgrade to php6.5 to see if the error persists.

**Comment by vishtany** [comment]
just probed the rest of the app at a glance, everything else seems to work except for this page

I see nothing thing the following executed code to cause this issue.
` Flight::route('/auth/login', function () {    
    if (isset($_POST['user'])&&isset($_POST['pass'])) { // if passworrd and username is selected
        $user = $_POST['user'];
        $pass = encrypted_pass($_POST['pass'])
        # what sort of user is this?
        $aID = accountID($user);
        // does this user exist?
        $accountexist = account_exists($aID);
        if ($accountexist == true) {
            $ud = account_data($aID); // get user data
             if ($ud['password'] === $pass) {# They Match"
                $_SESSION['accountID'] = $ud['accountID'];
                //$tlang = getAccountLang($ud['accountID']);
                // notification and ip/usergent log
                //addNotification($_SESSION['accountID'],'login');                
                //if ( !empty($tlang) ) { $_SESSION['lang'] = $tlang; }
                $_SESSION['timestamp'] = time();
                # redirect the ser to the home page
                    redirect('index');
                } else { // if passwords don't match
                   redirect("login?e=2");
                }
        } else {
            // redirect to login page with an error message
            redirect("login?e=1"); // the user does not exist
        }
    } else {
        // redirect with the first level error
        redirect('login?e=0');
    }
});`

**Comment by mikecao** [comment]
The line starting from #0 is just the stack trace. There should be an error message before that.

**Comment by vishtany** [comment]
Ok, found the problem after editing the error display before doing a `die(var_dump($ex));`
