### ISSUE TITLE
i want to get  ?argument from url

### ISSUE THREAD

**Issue by marcdakar** [flightphp/core#317]
hello,
i have different urls
/de/kat1
/de/kat1/sub2
/de/kat1?page2
/de/kat1/sub2?page2

can i design the route to get the last parameter ( ?page2) separatley if he exists

something like Flight::route('/de(/@kat(/@sub(/@nav)))@last', function( $kat, $sub, $nav, $last){ })

i need to fetch the ?parameter

thank you 
marc

**Comment by fabioars** [comment]
You can use super global $_GET to have access those variables in this case

**Comment by fabioars** [comment]
You don't need to register those variables on Flight router too

**Comment by marcdakar** [comment]
you are right, thanks !
