### ISSUE TITLE
Use Blade Template as default?

### ISSUE THREAD

**Issue by vishtany** [flightphp/core#318]
@mikecao  Would you integrate the blade template language as the default template language engine? Just wondering if you would be open to the idea? 

i have personally used the following within Flight for blade support which has been an amazing addition. => [Ducan3D Blade](http://duncan3dc.github.io/blade/)

**Comment by mikecao** [comment]
The default template in Flight is just plain PHP. That will always be the best default because it has no dependencies. But you can easily override the template engine to whatever you want. See the documentation example where it uses Smarty instead of the default.
