### ISSUE TITLE
Question: Good documentation language/tool for rest apis?

### ISSUE THREAD

**Issue by pascalBokBok** [flightphp/core#319]
I've done some projects ind Flight and have really enjoyed it.
Each time I've written the api doc in a txt format - while that works it requires working very structured and is not particularly great for navigating (no hyperlinks).
What tool do you suggest to create api docs?
Simple but competent is good.

**Comment by ghost** [comment]
I'm not sure that this is the best forum for the discussion of general API documentation software (perhaps stackoverflow would be a better choice), but I can provide information about the specific documentation used for http://flightphp.com (the repository is also open source and may be found here: https://github.com/mikecao/flightphp.com)

The documentation is built using Jeckyl (https://jekyllrb.com/docs/home/), a static site generator which takes HTML, CSS and an unprocessed markup language (such as Markdown) and transforms it in to flat HTML.

As http://flightphp.com is a relatively simple website, it's repository makes for a great example / intro to the Jeckyl platform and I would advise taking a look at the code to gain a foundational understanding, in particular the following files:

 - https://github.com/mikecao/flightphp.com/blob/master/_config.yml  
 - https://github.com/mikecao/flightphp.com/blob/master/_layouts/default.html  
 - https://github.com/mikecao/flightphp.com/blob/master/_includes/head.html  
 - https://github.com/mikecao/flightphp.com/blob/master/en/learn.html
