### ISSUE TITLE
Add examples with auth and/or jwt auth

### ISSUE THREAD

**Issue by unclesamwk** [flightphp/core#320]
Hey,

very great useful framework.
Please add examples with auth and/or jwt auth

Thanks

greetings 
Sam

**Comment by fabioars** [comment]
For Auth you can use [PHP session lib](http://us3.php.net/manual/en/book.session.php), a great example is [panique/php-login-minimal](https://github.com/panique/php-login-minimal). For JWT, I recoment use [firebase/php-jwt](https://github.com/firebase/php-jwt).

**Comment by sah-comp** [comment]
The correct link to  php-login-minimal is indeed [panique/php-login-minimal](https://github.com/panique/php-login-minimal).

**Comment by fabioars** [comment]
Thanks @sah-comp.
