### ISSUE TITLE
Regex groups not working for routes

### ISSUE THREAD

**Issue by Traderjoe95** [flightphp/core#324]
I'm trying to do routing with approximately 10 possible values for each path segment. Currently, I am trying to accomplish this using a pattern like `/@segment1:(val1|val2|val3|...|val10)/@segment2:(val1|val2|...|val10)`. All these paths are handled equivalently, the only difference is that data is fetched from different database tables.

The result are corrupted parameter values - none of them contains the correct segment. Is there a way to escape the parentheses so they do not get interpreted as optional parts of the route pattern? Can you think of a solution other than matching the regex in the callback code?

**Comment by mikecao** [comment]
You should just do a simple match and handle it further down in your code rather than relying on regexes.

```php
Flight::route('/@segement1/@segment2', function($segment1, $segment2){
   // Handle parameters
  if (in_array($segment1, $valid_values)) ...
});
```

**Comment by Traderjoe95** [comment]
Thank you for the quick response, I'll do it this way.
