### ISSUE TITLE
Documentation Unclear on How to Route Object Method With Parameters

### ISSUE THREAD

**Issue by OccamsRazorCoder** [flightphp/core#327]
So if I want to call   $PE->POST_Registration($departmentTypePK,$first,$last,$email,$password,$confirm);

Documentation Alludes to doing something like this:

Flight::route('/register/POST_Registration/@departmentTypePK/@first/@last/@email/@password/@confirm',  array($PE,'POST_Registration','departmentTypePK','first','last','email','password','confirm'));

Would you please point me in the right direction on how to make this call?    Does documentation exist or how do I make the call? 

Thx!

**Comment by williamcastro** [comment]
> Errors and Exceptions
> All errors and exceptions are caught by Flight and passed to the error method. The default behavior is to > send a generic HTTP 500 Internal Server Error response with some error information.

Please verify: [Error handling](http://flightphp.com/learn/#errorhandling)

---

Anyway you can simple call: 

`Flight::set('flight.handle_errors', false);`

And you will use the default PHP error mesages.

**Comment by williamcastro** [comment]
If you are going to pass the informations throw the URL, you will use GET, in this case I would probably do something like:

```php
class Register {
    public function POST_Registration($departmentTypePK, $first, $last, $email, $password, $confirm) {

        echo $departmentTypePK."<br>";
        echo $first."<br>";
        echo $last."<br>";
        echo $email."<br>";
        echo $password."<br>";
        echo $confirm."<br>";
    }
}

// I'll call GET to only accept informations coming from GET, if you don't pass anything it will accept GET and POST data 
Flight::route('GET /register/POST_Registration/@departmentTypePK/@first/@last/@email/@password/@confirm', function($departmentTypePK, $first, $last, $email, $password, $confirm) {
	$PE = new Register();
	$PE->POST_Registration($departmentTypePK, $first, $last, $email, $password, $confirm);
});
```

If you prefer to use POST (I highly recommend from my experience), I would do in this way:

```php

class Register {
    public static function POST_Registration() {
        echo $_POST['departmentTypePK']."<br>";
        echo $_POST['first']."<br>";
        echo $_POST['last']."<br>";
        echo $_POST['email']."<br>";
        echo $_POST['password']."<br>";
        echo $_POST['confirm']."<br>";
    }
}

// This is the shortest way, but you can do in the way I did the GET 
Flight::route('POST /register/POST_Registration/', array('Register','POST_Registration'));
```

**Comment by jimlei** [comment]
Normally you would use the URL only for knowing _what_ type of object to store, and pass the data as normal form data (POST). The URL doesn't really matter, but it is seen and used by both users and developers so it's a good idea to try to make a sensible URL scheme.

```php
/**
 * register new user in department
 * example: /department/13/register
 */
Flight::route('/department/@departmentId/register', array($PE, 'POST_Registration'));
```

```php
class PE {
  public function POST_Registration($departmentId) {
   $user = new User();
   $user->addDepartment($departmentId)
        ->setFirstName(Flight::request()->data->first)
        ->setLastName(Flight::request()->data->last)
        ->setEmail(Flight::request()->data->email)
        // ...
  }
}
```
