### ISSUE TITLE
Turn off Flights Interception / Call Stack of PHP Error Messages

### ISSUE THREAD

**Issue by OccamsRazorCoder** [flightphp/core#328]
While I do like the stack trace idea behind Flight's interception of PHP error messages, there is something I can't stand.    That is it truncates the actual error message thus clipping off vital information.   LOL.  Horrible!   Just let the error messages flow through from the server, don't doctor them up in any way shape or form.

**Comment by williamcastro** [comment]
>Errors and Exceptions
> All errors and exceptions are caught by Flight and passed to the error method. The default behavior is to > send a generic HTTP 500 Internal Server Error response with some error information.

Please verify: [Error handling](http://flightphp.com/learn/#errorhandling)

----
Anyway you can simple call:

`Flight::set('flight.handle_errors', false);`

And you will use the default PHP error mesages.
