### ISSUE TITLE
failed to route DELETE  in php 5.3.29

### ISSUE THREAD

**Issue by Yinux** [flightphp/core#330]
It works fine with the following code 
`Flight::route('/wgitem',array('Item','listItem4'));`
using DELETE method ,but this code failed 
`Flight::route('DELETE  /wgitem',array('Item','listItem4'));`
It turns out a 404 error.
and what's more  I use php 5.3.29

**Comment by mikecao** [comment]
How are you sending the DELETE request?

**Comment by Yinux** [comment]
postman in chrome

**Comment by Yinux** [comment]
at the beginning  I use  [webix](https://docs.webix.com/desktop__server_rest.html) the front ,but failed,then I test it with postman.

**Comment by mikecao** [comment]
Flight gets the value from `$_SERVER['REQUEST_METHOD']`. Do a var_dump and see if it is being set correctly by the server.

**Comment by Yinux** [comment]
Thanks ,I find it .you can route `DELETE /url`,but can not route `DELETE  /url` .
That is to say ,you can only use **one** space between method and url
