### ISSUE TITLE
Route Middleware

### ISSUE THREAD

**Issue by FrancescoASessa** [flightphp/core#332]
Hi, it's possible to integrate Middleware in route like [this](https://laravel.com/docs/5.4/routing#route-groups)? 
Thanks

**Comment by mikecao** [comment]
Currently no. It will need to be an enhancement.

**Comment by FrancescoASessa** [comment]
Thanks. :)

_Sent from my HUAWEI VNS-L31 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by n0nag0n** [comment]
This is currently being implemented with #514
