### ISSUE TITLE
IRC Channel

### ISSUE THREAD

**Issue by Conver** [flightphp/core#333]
I've created #FlightPHP channel on IRC network Freenode, please join and lets discuss FlightPHP, everybody is welcome.

**Comment by aolko** [comment]
IRC is slow, try [Discord](http://discordapp.com)
###### (Also, self-like, really?)

**Comment by jimlei** [comment]
Ok sorry for going OT but I got really curious. How is IRC slow..?

**Comment by aolko** [comment]
you basically have to wait all day for an answer, no notifications (generally), lots of idlers, no type indication (therefore you cannot predict when answer is being typed)

**Comment by Conver** [comment]
@aolko, If you dont like IRC, just simply dont join. We are many others who likes IRC and uses it daily.
