### ISSUE TITLE
Flight::json duplicating arrays on latest, working on v1.1

### ISSUE THREAD

**Issue by chaddoncooper** [flightphp/core#337]
Using PHP 5.3.3 (yes, I know), encountering duplicated JSON arrays being sent when using the built in flight::json function to encode an array of anything.
If I echo json_encode all is well.
Switching back to 1.1, maybe somebody could shed some light on why this is happening. If there is interest I can provide more details later.

**Comment by mikecao** [comment]
Confirmed. I'll provide a fix soon.

**Comment by mikecao** [comment]
Fixed in latest version e146b8c0ddbc6384c5a66f23dea71743fc282289.
