### ISSUE TITLE
curl timeout

### ISSUE THREAD

**Issue by TonyChen-SH** [flightphp/core#338]
i use this curl class(https://github.com/php-mod/curl).  
```
$recharge = new Recharge();
Flight::route('/recharge/submit', array($recharge, 'submit'));

// Recharge class
// sumbmit method
$curl = new \App\Service\Curl();
        $url = $_SERVER['HTTP_HOST'];
        $curl->get("http://" . $url . "/recharge/api", $submit);
        if ($curl->error) {
            $ret = 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        } else {
            $ret = $curl->response;
        }
```
annother router
```
Flight::route('/recharge/api', array($recharge, 'api'));
// Recharge class
// api method
echo 11
```
/recharge/api is not response. but curl is time out. it receive the request.  I don't understand why that is

**Comment by TonyChen-SH** [comment]
OS: windows7

**Comment by mikecao** [comment]
If you type in `/recharge/api` in the browser do you get a response?

**Comment by TonyChen-SH** [comment]
yes. I can get a response in the browser.

**Comment by mikecao** [comment]
Sounds like you have a problem with curl and not Flight.

**Comment by TonyChen-SH** [comment]
But I don't know why. I can provide code. Can you help me see the reason?

**Comment by TonyChen-SH** [comment]
I used another way to make it work~ Thank you very much
