### ISSUE TITLE
Halt method does not stop execution

### ISSUE THREAD

**Issue by kouts** [flightphp/core#341]
After latest changes the ```halt``` method does not stop execution.
I've created the #340 PR for this.

**Comment by mikecao** [comment]
PR merged.

**Comment by kouts** [comment]
I think I hurried a bit on this one, ```halt``` method does not stop execution event after calling ```clear```.
Since the ```exit``` statement is now removed from the Response class, the ```exit``` statement must be added to the ```halt``` method like this:
```
    public function _halt($code = 200, $message = '') {
        $this->response()
            ->clear()
            ->status($code)
            ->write($message)
            ->send();
        exit();
    }
```
Please confirm so that I can submit a second PR for this.

**Comment by kouts** [comment]
To add on this, I thnk```exit``` should be now added to the redirect method as well.

**Comment by mikecao** [comment]
You're right that halt should exit, but that is probably the only one since the user explicitly asked for the framework to exit. Other methods should allow all before/after filters to run.

**Comment by kouts** [comment]
Shouldn't redirect exit?

**Comment by mikecao** [comment]
The redirect will still happen. But if you added a filter like `Flight::before('stop', $logSomething)`, then it will never run if you exit. The point of removing exit from the response is so filters could run, with halt being the one exception.

**Comment by kouts** [comment]
Ok, thanks for the explanation, I've submitted the PR #342
