### ISSUE TITLE
Status Code always 200

### ISSUE THREAD

**Issue by vic4key** [flightphp/core#343]
Hi everybody,

I want to send a status code to client eg. 400, 404, etc. same as function http_response_code().
But Flight always returned 200.
I've already tried Flight::response()->status(400) but it's still returned 200.
I googled but found no way to do this.
Could you please help me to do it?

Thanks !

**Comment by mikecao** [comment]
What does your route look like? For example this should work:
```php
Flight::route('/status', function() {
    Flight::response()->status(404);
    echo 'The status is 404.';
});
```

**Comment by vic4key** [comment]
![screenshot_2017-10-23_00-08-41](https://user-images.githubusercontent.com/5672864/31864373-6c7e75aa-b786-11e7-855d-d1e73fbd0a41.png)

With your code. It looks like this, bro. Still returned 200.

**Comment by mikecao** [comment]
You must have something different in your setup. Maybe Apache is rewriting the response. I have a simple setup with only one route and it gives the right status code.

![image](https://user-images.githubusercontent.com/477975/31864683-9daa9868-b716-11e7-87c4-2da20e6a826c.png)

**Comment by vic4key** [comment]
I'm using the default rewrite url code in your instruction.
My site is working in a sub folder of the root. The url of index.php is *localhost/JSTools/index.php*.
Is it okay, bro? Could you please tell me what's wrong?

**Comment by mikecao** [comment]
I don't know, you need to troubleshoot your setup. You can try running through a local PHP server using `php -S` and see what happens.

**Comment by kouts** [comment]
@vic4key can you try ```Flight::response()->status(400)->send();``` to see if that works?

**Comment by vic4key** [comment]
@mikecao  Thanks you, bro. I'll try it after I come back home. I'm being in office now.
@kouts  Hi. I tried it and the result I posted at comment #3 above (attached image). They are the same result.
I think, because of Re-write URL as @mikecao mentioned.

**Comment by vic4key** [comment]
Oops. Everything is default. A simple issue but hard to solve. I tried many way to solve, but failed, all. What's pity.

![screenshot_2017-10-23_23-35-11](https://user-images.githubusercontent.com/5672864/31901284-302be8ec-b84b-11e7-980f-148c1f25ee25.png)

![screenshot_2017-10-23_23-42-03](https://user-images.githubusercontent.com/5672864/31901500-cbce2058-b84b-11e7-8591-cf50fae9843f.png)

![screenshot_2017-10-23_23-41-49](https://user-images.githubusercontent.com/5672864/31901501-cc097432-b84b-11e7-873e-9796c2dd2470.png)

**Comment by williamcastro** [comment]
Did you try, to run through PHP Server, like Mike Cao suggested?

Edit:
I only have servers with Nginx. I tried same code you are using and worked.

![will](https://user-images.githubusercontent.com/154308/31902629-3ef8087a-b804-11e7-9bb7-4d0d10748dd8.png)

I think it's a problem with your setup (apache overwriting headers?)

**Comment by vic4key** [comment]
Of course, friend. I tried all their suggestions. Same result. So strange. I'm finding a new solution.

**Comment by williamcastro** [comment]
What is the PHP Version? Are you using FastCGI?

**Comment by vic4key** [comment]
I'm using PHP 5.6 (XAMPP 5.6.31-0 on Linux). I'm not sure about FastCGI but CGI module is enabled and runnable. But I don't think so that related to CGI/FastCGI.

**Comment by williamcastro** [comment]
Try to create a New php file, and put:

`<?php
header('X-PHP-Response-Code: 404', true, 404);
?>`

What your browser returns.

**Comment by vic4key** [comment]
It's normal. Returned 404. I also tried with http_response_code(404) before and it's worked.
This is the reason that I said it did not relate to PHP version or CGI/FastCGI.

PS : I also tested on both Linux and Windows and it is the same result, always 200. So strange. :(

**Comment by williamcastro** [comment]
Try to ` <?php echo php_sapi_name(); ?>` , to see what returns, I don't know, maybe it could be something detecting the CGI/FastCGI.

In the flight/Response.php

```php        // Send status code header
        if (strpos(php_sapi_name(), 'cgi') !== false) {
            header(
                sprintf(
                    'Status: %d %s',
                    $this->status,
                    self::$codes[$this->status]
                ),
                true
            );
        }
        else {
            header(
                sprintf(
                    '%s %d %s',
                    (isset($_SERVER['SERVER_PROTOCOL']) ? $_SERVER['SERVER_PROTOCOL'] : 'HTTP/1.1'),
                    $this->status,
                    self::$codes[$this->status]),
                true,
                $this->status
            );
        }`

**Comment by vic4key** [comment]
OMG. Seems right. It returned *apache2handler*. Maybe this is the reason always returned 200.
So I need to change it to CGI or FastCGI, right, bro?
Could you please tell me how to do it?
I checked *httpd.conf*, all CGI are using *LoadModule*.

**Comment by williamcastro** [comment]
Not Exactly, it's only shows that you are not using FastCGI, it's help me trying to reproduce your error here, to help you find a solution.

**Comment by vic4key** [comment]
Yes. Professional. Thanks you. Thanks you so much helped me find the reason.
I will try to find a solution.
Anyway, it should be noticed/mentioned in the instruction/document or do something else to make it more easier.

Thanks @williamcastro, @mikecao and others helped me so much.

**Comment by williamcastro** [comment]
It should work fine, without FastCGI, i only asked to help me to reproduce your dev. environment.

**Comment by vic4key** [comment]
Yes I think so. I also tried to modify that code in *Response.php* for checking again.
It is the exact reason.
Do you think, need to update to make it work fine without CGI/FastCGI, @mikecao?

**Comment by williamcastro** [comment]
**## Edit: In my Apache (PHP 7), I wasn't using the last flight version, updated and the status code is working perfectly now.**

@vic4key Are your flight in the latest version?

--

@mikecao  I tried here to reproduce @vic4key  error.
In my Nginx (PHP 7), it works fine and return the '400';

With Apache (PHP 7), the code "Flight::response()->status(400);", returns 200.

In the file: /flight/net/Response.php

The function status(), is receiving the 400 code:
```php
    /**
     * Sets the HTTP status of the response.
     *
     * @param int $code HTTP status code.
     * @return object|int Self reference
     * @throws \Exception If invalid status code
     */
    public function status($code = null) {
        if ($code === null) {
            return $this->status;
        }
        if (array_key_exists($code, self::$codes)) {
            $this->status = $code;
        }
        else {
            throw new \Exception('Invalid status code.');
        }
        return $this;
    }
```

But when it sends to the browser, "$this->status" is 200. I don't know why it's resetting. 

```php   
    /**
     * Sends HTTP headers.
     *
     * @return object Self reference
     */
    public function sendHeaders() {	
        // Send status code header
        if (strpos(php_sapi_name(), 'cgi') !== false) {
            header(
                sprintf(
                    'Status: %d %s',
                    $this->status,
                    self::$codes[$this->status]
                ),
                true
            );
        }
```

I hope this help you in someway!

**Comment by vic4key** [comment]
I printed stack trace with following one line code on *Response.php* : 

```
    public function send() {
        if (ob_get_length() > 0) {
            ob_end_clean();
        }
        print_r(debug_print_backtrace()); # <= HERE
        if (!headers_sent()) {
            $this->sendHeaders();
        }

        echo $this->body;
    }
```
Probably the error comes from `<h1>500 Internal Server Error</h1><h3>Cannot modify header information - headers already sent by (output started at /opt/lampp/htdocs/JSTools/vendor/mikecao/flight/flight/net/Response.php:270) (2)</h3><pre>#0 [internal function]: flight\Engine->handleError(2, 'Cannot modify h...', '/opt/lampp/htdo...', 234, Array)`.

Log : [log.txt](https://github.com/mikecao/flight/files/1408520/log.txt)

**Comment by williamcastro** [comment]
@vic4key , verify if you are using the last version of Flight, 4 days ago (commit e146b8c0ddbc6384c5a66f23dea71743fc282289), changed the function send(), i think this solve your problem. Because when I reproduced your error, I was using an old version without `$this->sent = true;`.

**Comment by mikecao** [comment]
@williamcastro When you run `php_sapi_name()` from apache what do you get?

**Comment by williamcastro** [comment]
I get: **cgi-fcgi** 

I updated the flight version I was using, and now the apache server is working (returning the right code)
