### ISSUE TITLE
Is there a changelog?

### ISSUE THREAD

**Issue by Augenpulver** [flightphp/core#346]
I just run composer update and this updated flight from 1.3.2 to 1.3.5 but I have no idea what has changed and if I have now to make some code changes. Is there a changelog where I could read what these changes are?

**Comment by mikecao** [comment]
Sorry no official changelog, but you can view the descriptions of changes on the tags screen, https://github.com/mikecao/flight/tags

**Comment by anotherdevs** [comment]
Hi @mikecao 

I can see that you bumped to version 1.3.6: https://github.com/mikecao/flight/commit/db2c5c77e147a31c0e1fbb8fd715b9e65d763af3 but latest release is 1.3.5: https://github.com/mikecao/flight/releases

Can you add a new tag/release?

**Comment by mikecao** [comment]
@anotherdevs New tag released. Forgot to bump the version when I merged the latest change, thanks for spotting it.
