### ISSUE TITLE
How to register Meedo Database framework?

### ISSUE THREAD

**Issue by mukitti2014** [flightphp/core#348]
How can I register Meedo class to Flight  ?

use Medoo\Medoo;
 
$database = new Medoo([
	// required
	'database_type' => 'mysql',
	'database_name' => 'name',
	'server' => 'localhost',
	'username' => 'your_username',
	'password' => 'your_password',
	'charset' => 'utf8',
	'option' => [
		PDO::ATTR_CASE => PDO::CASE_NATURAL
	],
]);

**Comment by saitergun** [comment]
i did this
```php
use Medoo\Medoo;

$medoo_Config = [
	"database_type" => "mysql",
	...
];

Flight::register( "db", new Medoo( $medoo_Config ), [ $medoo_Config ] );
```

**Comment by rajkumarpb** [comment]
@mikecao  I have registered Medoo class as you mentioned and trying to use like below. But its not working.

```
Flight::route('GET /getclients', function(){
    $conn = Flight::db();   
    $data = $conn->select("client", [
        "[>]state" => ["client_state" => "state_id"],
        "[>]country" => ["client_country" => "country_id"],
    ]);
    echo json_encode($data);
});
```
