### ISSUE TITLE
Can't accept uploaded file

### ISSUE THREAD

**Issue by ghost** [flightphp/core#352]
Hello and thank you!
But, i'm trying to send from PowerShell REST PUT request and extract file and save him to disk. But no nothing accepted..
PowerShell:
$uri = "http://localhost/file"
$filePath = "00002.spl"
$upload = Invoke-RestMethod -Uri $uri -Method Put -InFile $filePath
Write-Host $upload

PHP:
require 'vendor/autoload.php';
Flight::set('flight.log_errors', true);
Flight::route ( 'PUT /', function () {
	echo 'PUT method ';
	$files = Flight::request ()->files;
	foreach ( $files as $key => $value ) {
		echo 'Key: '.$key.', value = '.$value;
	}
} );

Flight::start ();

Answer:
"
PUT method"

**Comment by mikecao** [comment]
Do a `var_dump` of the entire request object and see what is coming across.
