### ISSUE TITLE
Can I disable Flights autoloader and use composer instead?

### ISSUE THREAD

**Issue by Brainshack** [flightphp/core#353]
Hello,

is there a way to disable autoloading inside Flight and Use composer for autoloading instead? I need Flight to go through composers autoloader to be able to use it with goaop. Is there a way to do so?

**Comment by mikecao** [comment]
Flight's autoloader is enabled in `autoloader.php`. You can try editing the package.json file to not load that file.

**Comment by lisachenko** [comment]
Alternatively, you could call `spl_autoload_functions()`, search for Flight's autoloader and unregister it from class loaders stack or move it down.

**Comment by n0nag0n** [comment]
Seems addressed.
