### ISSUE TITLE
I got 404 after switch fastcgi php-fpm

### ISSUE THREAD

**Issue by dingzhanjun** [flightphp/core#354]
My site worked fine, after switching to fastcgi, I got 404 error for every path, but the regular php works. can anyone please help?  Thanks!
Evn:
Apache 2.4
Ubuntu 14.04
php 5

**Comment by angarsky** [comment]
The same issue. I get 404 status, but a page is delivered. Detected this error after an update from the v1.3.2 to the v1.3.5. The v1.3.2 worked fine.

The issue is not reproduced at my local machine (PHP is a Apache module), but it reproduced on a stage instance (PHP-FPM, nginx - Pantheon hosting).

**Comment by magikstm** [comment]
Seems like a webserver or .htaccess issue and not a FlightPHP one.

I think this issue can be closed.

**Comment by n0nag0n** [comment]
I agree.
