### ISSUE TITLE
IP FILTER get error

### ISSUE THREAD

**Issue by MartinsYong** [flightphp/core#356]
when test the "index.php" from the repository, i got this error:
"Fatal error: Undefined constant 'FILTER_FLAG_NO_PRIV_RANGE' in /www/flight/net/Request.php on line 248"

**Comment by mikecao** [comment]
What version of PHP are you using? Do you have the filter extension enabled? http://php.net/manual/en/book.filter.php

**Comment by MartinsYong** [comment]
PHP Version 5.6.32
i think the filter is enabled by default.

**Comment by mikecao** [comment]
Create a new file and just run this:

```
<?php
vardump(filter_var(
  '192.168.0.1,
  FILTER_VALIDATE_IP,
  FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE
));
?>
```

If you get an error there is something wrong with your install.

**Comment by MartinsYong** [comment]
Thanks!!
