### ISSUE TITLE
I have got problem with Flight::register(...)

### ISSUE THREAD

**Issue by Numpek2k** [flightphp/core#357]
This is my index.php:
![image](https://user-images.githubusercontent.com/33579708/35914902-49d62b46-0c05-11e8-8306-89b8772eee85.png)

in this file I registered connection to the database.
When i tried to use this class in another file
![image](https://user-images.githubusercontent.com/33579708/35915219-4e584a72-0c06-11e8-8ec6-ea83b191a2bd.png)
, it is said that 
![image](https://user-images.githubusercontent.com/33579708/35915273-77b5cb88-0c06-11e8-8454-ff2deaf17bb4.png)
Sry but I'am just beginner with Flight :|

**Comment by mikecao** [comment]
You can't call `start` before setting everything up.

**Comment by Numpek2k** [comment]
So, when I change it, I seen an error :
![image](https://user-images.githubusercontent.com/33579708/35939477-8662cf0a-0c4c-11e8-84e2-6af910ccf4c6.png)
