### ISSUE TITLE
Flight::stop() doesnt work in v1.3.5

### ISSUE THREAD

**Issue by ghost** [flightphp/core#362]
I have the following function that i use to return an error. This works fine in v1.3.3 but if i use v1.3.5 it continues on with the script and doesn't exit. Has the functionality recently changed?

```
    public static function ReturnError($Code, $Error = null)
    {
        $ErrorArray = array('error' => $Error);
        print Flight::json($ErrorArray, $Code, true, 'utf-8', JSON_NUMERIC_CHECK);
        Flight::stop();
    }
```

**Comment by mikecao** [comment]
There was a change so that stop wouldn't exit automatically so that you could do things in post filters. If you want an immediate exit you can just call exit() after the json call. Also the json method doesn't return anything to print, it just sends a json response.
