### ISSUE TITLE
Intercepting file requests as routing paths

### ISSUE THREAD

**Issue by marekjedlinski** [flightphp/core#365]
In Flight, I have a route for requests to download an ebook file:

    Flight::route('/download/@dl_format', function($dl_format){
        // $dl_format may be 'epub' or 'mobi'
        echo "Download request: ", $dl_format;
    });

This works. But the files reside on the server, and I want this route to trigger even if the original URI is, for example, `http://example.com/file.epub`. I've been trying to achieve this by a rule in .htaccess:

    RewriteRule (epub|mobi)$ /download/$1 [QSA]

but the /download/ route is never triggered, and I can only capture this request using a catch-all route '*' (but then i still cannot see the `/download/format` part). Is there a way to get this to work using Flight?

Edit: in other words, is there a way to do either of the following:

- rewrite an arbitrary URL in htaccess so that Flight will see it as `/some/route` instead of the original URI; or
- handle arbitrary URLs in Flight when they do not conform to the `/some/route` format? (For example, how does one work with query strings inside Flight's route handlers?)

**Comment by marekjedlinski** [comment]
No solution really, but a workaround I'm using is to rewrite file requests to a query string in .htaccess, and then, in Flight, intercept file requests using a catch-call `/*` route and check the query string there.

**Comment by mikecao** [comment]
The way Flight works is you rewrite all requests to a single file and it will process the request url. If you add additional rewrite rules, you are circumventing that process so unpredictable things will happen.

To access query string parameters just do `$id = Flight::request()->query['id'];`.
