### ISSUE TITLE
Output buffering started, never flushed

### ISSUE THREAD

**Issue by marekjedlinski** [flightphp/core#366]
In `Engine::_start()`, output buffering is unconditionally enabled (Engine.php, line 326 in the current version), and the buffer is never flushed/ended in code.

If I understand it correctly, it means that after calling Flight::start(), anything my code outputs will be buffered and sent only when the script exits.  This is quite bad for some contexts. For instance, if I deliver a binary file via my php script (which I do, to keep a download count), then the whole file will be buffered in the server's memory, instead of getting progressively sent out in pieces.

Could you please confirm whether this is indeed the case?

**Comment by mikecao** [comment]
Yes, Flight builds a HTTP response object to send, so it buffers all output to include in the response. You can still handle the response yourself if needed. When your route callback is called, run whatever code you want and call exit().
