### ISSUE TITLE
Class with namespace in the callback function fails!

### ISSUE THREAD

**Issue by FarhanShares** [flightphp/core#370]
Assume the simple class with namespace and without namespace, then these happen..
-------------
Namespace Abc;

Class Home {
	public function index(){
        Echo "hi";
        }
}
------------
WORKS:
Flight::route('GET /', ["Home", 'index']));

NOT WORKING:
Flight::route('GET /', ["Abc\Home", 'index']));

What's the solution here?

**Comment by mikecao** [comment]
I think you need to use the fully qualified namespace `\Abc\Home`, or add a `use` statement. Also your method isn't static so you'd have to create and instance first.

**Comment by FarhanShares** [comment]
I've already tryed whatever you've mentioned with no luck. Static method and fully qualified namespace, both was applied combinely and separately which returned 500 internal server error with callback error message (forget the message, this was what dispatcher::invokMethod() callback error text set).

**Comment by mikecao** [comment]
You'll have to post the full error. This is most likely a PHP error and not an issue with Flight.

**Comment by SaphiLC** [comment]
found a solution? :(

**Comment by FarhanShares** [comment]
I've fixed it and did a lot of modifications, thats why I forgot what  exactly made this working.
