### ISSUE TITLE
Wildcard and optional parameters

### ISSUE THREAD

**Issue by simar88** [flightphp/core#372]
Hi everyone,
i'm trying to figure it out a route where i can have an optional parameter together with a wildcard.
I would like to use something like this:
`Flight::route('/(@lang/)*', function($lang, $route){})`
but is giving me some errors.
If i'll continue to have issues, i think that i'll use a method that will split the array defined by **$route->splat** and then check the first value.
Do you have some tips on how to implement, if it is possible, this thing using **Flight::route**?

**Comment by mikecao** [comment]
I think you can just use two routes:

```php
Flight::route('/@lang/*', function($lang) {
  // check if lang is valid
  if (!check_lang_valid_func($lang)) {
    // not valid then continue to next route
    return true;
  }
}
```

And then another route without the `@lang` parameter.

**Comment by sah-comp** [comment]
I remember we [discussed some similar issue](https://github.com/mikecao/flight/issues/39) a while ago.

**Comment by simar88** [comment]
Hi guys thanks for your help!
Looking better my code and your resource i found that i was using the right approach for my needs and i was only wrong with writing the route.
I implemented the call in this way and made some controls by my own with a custom class.



```
Flight::route('(/@lang:[a-z]{2})/*', function ($lang) {
if (!empty($lang)) {
     // if present try to set it as default        
    Flight::language()->setLang($lang);
} else {
   // detect the lang from cookie or browser setting
   Flight::language()->detectLang();
}
   //compare the current lang with the others available for the website
  Flight::language()->checkLang();
  return true;
});
