### ISSUE TITLE
only a blank between HTTP method and uri?

### ISSUE THREAD

**Issue by TuringZhu** [flightphp/core#373]
I found that when I specified HTTP Method in route method, only one blank can be hold between HTTP method and uri. does it support one or more blank?

```php
Flight::route('GET /helloworld', function(){  // only one blank between 'GET' and '/helloworld'
    echo 'Hello World!';
});
```

the related code in [`Line 65-66` of `File flight/flight/net/Router.php`.](https://github.com/mikecao/flight/blob/master/flight/net/Router.php#L65)

**Comment by mikecao** [comment]
You should only enter one blank space.

**Comment by TuringZhu** [comment]
all right!
