### ISSUE TITLE
Return Images from API

### ISSUE THREAD

**Issue by ianmiddelkamp** [flightphp/core#376]
Hello, Perhaps this is related to issue #366, not sure.

I am trying to send an image file back to an android device through my API. I have tried several different ways to do this. The php class function which reads the image is as follows:
```
   public function getEmployeeImage($EmployeeId){
        $filepath = "../images/employees/" . $EmployeeId . ".jpg";
        if(file_exists($filepath)){
            $file = fopen($filepath, "rb");
            $contents = fread($file, filesize($filepath));
           
           return $contents;
        }else{
           return null;
        }
    }
```

and my route looks like this: 

```
Flight::route("GET /Image/Employee/@EmployeeId", function ($EmployeeId) {
    //echo "TEST";
    require_once '../include/FileManager.php';
    $RequestHandler = new FMRequestHandler();
    header('Content-Type: image/jpeg');
    $content = $RequestHandler->getEmployeeImage($EmployeeId) ;
    echo $content;
    exit();
    
    
});
```

I have also tried not setting the header content-type and also setting it to application/octet-stream. In the android code it saves this file and then later on it tries to decode it into a bitmap. The files are saving, but decoding is failing, and if I try to look at the image in its original state before decoding it is corrupted. However, if I just do my http request from the android device to the file on the server (instead of going through the API) it works fine. This leads me to believe that it is something to do with either the way I am reading the file in PHP or the way the API is sending the data. The android code is using Volley and is expecting an byte array.  Is there anything you can suggest? BTW my Flight API works great for JSON and I am loving it up to this point. 

Please help if you can.

**Comment by erkinsergey** [comment]
Hi! Maybe this will somehow help. 
I use the following working code in my projects route:
```
// $path - path to the file without file name 
// $file_name - something like 'myimage.jpg'
$full_name = $path . '/' . $file_name;
if (file_exists($full_name)) {
    header('Content-Description: File Transfer');
    header('Content-Type: ' . \FileUtils::getFileMime($full_name));
    header('Content-Disposition: attachment; filename="' . $file_name . "\"");
    header('Expires: 0');
    header('Cache-Control: must-revalidate');
    header('Pragma: public');
    header('Content-Length: ' . filesize($full_name));
    readfile($full_name);
    exit;
  }
```
Actually, this is an example from the readfile documentation:
http://php.net/manual/en/function.readfile.php

**Comment by ianmiddelkamp** [comment]
Thanks very much for your response. I did end up using these headers but I don't think that was the problem. I noticed in POSTMAN that responses from my API always have a number of blank lines at the start. I called ob_end_clean to clear the buffer and this works now. The bitmaps are decoding in the java code, and the files are no longer corrupted and display in POSTMAN. 

My code is as follows. 
```
//Event get employee image 
Flight::route("GET /Image/Employee/@EmployeeId", function ($EmployeeId) {

    require_once '../include/FileManager.php';
    $RequestHandler = new FMRequestHandler();
    $filename = $RequestHandler->EmployeeImageExists($EmployeeId);
   
   if(!empty($filename)){
        ob_end_clean();
        header('Content-Description: File Transfer');
        header('Content-Type: ' . mime_content_type ($filename));
     
        header('Content-Disposition: attachment; filename="' . basename( $filename) . '"');
  
        header('Content-Length: ' . filesize($filename));
   
        readfile($filename);
     
        exit;
    }else{
        echo null;
    }
 
});
```

**Comment by erkinsergey** [comment]
Very good. 
About empty lines ...
Maybe somewhere there are empty lines before **<? php** or after **? >**
```
<!-- empty line -->
<?php
// php code here
?>
<!-- empty line -->
```
or you use [UNICODE BOM](https://en.wikipedia.org/wiki/Byte_order_mark)?

**Comment by ianmiddelkamp** [comment]
Yes Sir, Empty lines before and after!! No need to clean the buffer! Thank you!
