### ISSUE TITLE
Redirect with parameters

### ISSUE THREAD

**Issue by xotik** [flightphp/core#377]
Hey everyone,

I´m not sure if this is an issue or a suggestion. I was looking for a way to `Flight::redirect()` with parameters, as it's done in render, for example:

`
Flight::render('auth/login', array(
            'title' => 'Login'
        ));
`

The docs state that redirect only accepts the url and redirect code, so I've been passing those parameters like this:

`
Flight::redirect('login&title=Login')
`

But that's ugly and I can´t take advantage of Flight::request() in the new page (says me, haven't tested it yet).

So is it a bug, am I doing anything wrong or it's just not an available feature? If it's not a feature, any plans to implement it?

Many thanks.

**Comment by mikecao** [comment]
All that `redirect` does is send you to a new url. The url posted is wrong, it needs to be `login?title=Login`.

**Comment by xotik** [comment]
Hey @mikecao,

Yep sorry about the typo, but that was not the point anyway.

Ok, so it's clear what `redirect` does...any plans in the future to support passing parameters as well?

Thanks :)

**Comment by mikecao** [comment]
Adding parameters through the query string is the proper way to do it. You can simply pull the parameters you need from `Flight::request()`. You can't pass an array because you are making a new HTTP request in a redirect and data is not preserved between requests.

**Comment by xotik** [comment]
Oh ok, I have to implement that, I was using the global $_POST and that was pretty ugly ahah.

Thanks for the help Mike.

By the way, when calling redirect(), if I don’t call exit() afterwards all I get is a blank page with the specified url echoed at the top.

Probably just some misconfiguration from my server, just letting you know in case you want to look into it.

Thanks again.
