### ISSUE TITLE
Trouble with PHP-FPM -  " ERR_SPDY_PROTOCOL_ERROR" on Google Chrome 

### ISSUE THREAD

**Issue by distrilog** [flightphp/core#378]
Append to me : create a simple website with Flight on OVH server, it appeared I had to desactivate PHP-FPM into the ovh server config file  "app.engine=phpcgi" instead of "app.engine=php" to make it work.

**Comment by mikecao** [comment]
Sorry this sounds like a server configuration issue rather than a framework issue.
