### ISSUE TITLE
Missing namespace at core class, not wanna use require

### ISSUE THREAD

**Issue by frantisekpetko** [flightphp/core#379]
Hello, please add namespace at core class Flight.php if it is possible, I don't want use import function "require" cause clean code :|  It will be good use: php import function "use" instead of "require" :) Thank you.

**Comment by spytheman** [comment]
@frantisekpetko Why do not you prepare a pull request with your desired change? That way it will be easier for the maintainer to merge it, and it will improve the chance of solving your issue.

**Comment by mikecao** [comment]
The Flight class was designed to be in the global namespace. If you want to load the internals you can use `flight\Engine`.
