### ISSUE TITLE
How can I override Flight::json()

### ISSUE THREAD

**Issue by crazedVic** [flightphp/core#381]
I would like to pass back additional headers, right now there’s no option to do so, so i’d Like to override the function on line 467 in Engine.php. Accept additional headers in an array, that sort of thing?

**Comment by erkinsergey** [comment]
Try
```
\Flight::map('json', function ($data, $code = 200, $encode = true, $charset = 'utf-8')
  {
   // your code here
  });
```

**Comment by n0nag0n** [comment]
Seems addressed
