### ISSUE TITLE
Flight::json() having issues with ' character (unicode?)

### ISSUE THREAD

**Issue by wolfscott** [flightphp/core#383]
Hitting an issue where I think some text was cut/pasted into a table field from something like msWord or other wordprocessor - doing a little debug and it appears to be a unicode single quote in the data - is there a way to override or add a way to handle these characters? Its causing issues in data format for the response when I do the Flight::json() ...  (seems to eat the response)  If I replace the suspected single quote in the db field with a "standard" single quote, all works as expected so hoping there was some encoding type option I could enable ...

thoughts?

**Comment by mikecao** [comment]
Here are the parameters you can pass to the `json` method:

```
    /**
     * Sends a JSON response.
     *
     * @param mixed $data JSON data
     * @param int $code HTTP status code
     * @param bool $encode Whether to perform JSON encoding
     * @param string $charset Charset
     * @param int $option Bitmask Json constant such as JSON_HEX_QUOT
     * @throws \Exception
     */
```

Try different `$charset` and `$option` values and see if it helps.
