### ISSUE TITLE
Sanitize Flight::request()->data

### ISSUE THREAD

**Issue by dynek** [flightphp/core#387]
Hey,

I really like using Flight, great stuff, thanks!

Is there a way to sanitize / modify stuff in Flight::request()->data "once for good"?
Was trying to work around dates (input type=date not working with Safari) and was wondering if this is something I could be doing prior to actually process the posted data.

Thank you

**Comment by mikecao** [comment]
You could add a hook `Flight::before('start', ...)` and in that you can do:
```php
// Get data from request
$data = Flight::request()->getData();

// Modify data
// ...

// Save the data
Flight::request()->setData($data);
```
