### ISSUE TITLE
Twig support

### ISSUE THREAD

**Issue by nosovk** [flightphp/core#388]
Could we use twig instead of smarty?

**Comment by erkinsergey** [comment]
Если можно, отвечу по-русски.
Я использую Twig следующим образом:

**Comment by erkinsergey** [comment]
Если можно, отвечу по-русски. 
Я использую Twig следующим образом:
```
\Flight::register('view',  'MyTwigView');
```
где класс MyTwigView в конструкторе содержит код инициализации Twig и метод render, который имеет вид:
```
public function render ()
{
  return $this->pTwig->render($this->$template_name, $this->data_for_render);
}
```
Пользоваться всем этим можно следующим образом:
```
$v = \Flight::view(['data'=>'value'], 'template_name.html');
echo $v->render();

```

**Comment by mikecao** [comment]
Yes, you can use any template engine you want.
