### ISSUE TITLE
no explicit namespace on class method routing raise Invalid callback

### ISSUE THREAD

**Issue by masakik** [flightphp/core#390]
Hi,
I am trying this:
```php
use \masakik\View\View;
Flight::route('/', ['View', 'test']);
Flight::start();
```
but it raises the invalid callback specified.

If I put the full path on the callback
```php
Flight::route('/', ['\masakik\View\View', 'test']);
```
it works fine.
Is there a way to set the namespace to be used on callbacks like the `use` statement?

**Comment by jimlei** [comment]
I think you'll need to pass in the object to do this

```php
use \masakik\View\View;

$controller = new View();
Flight::route('/', [$controller, 'test']);
Flight::start();
```

**Comment by masakik** [comment]
This option solves this issue. Thks.
