### ISSUE TITLE
force trailing slash or force remove trailing slash

### ISSUE THREAD

**Issue by PhoenixPeca** [flightphp/core#391]
Hi @mikecao,

This is a really nice project! Im so glad to integrate it into a big project of mine. One issue though, is that there is no built in easy way to force trailing slash or disable it altogether.

It would be nice to have this feature!

Thanks!

**Comment by FarhanShares** [comment]
Is there any update on this issue? How to fix this?

**Comment by krmu** [comment]
One of the last commits fixed this.  I hade same issue.
