### ISSUE TITLE
travis-ci and coveralls

### ISSUE THREAD

**Issue by magikstm** [flightphp/core#392]
Would you consider adding these to the main readme and to the repo?

I did a quick test and added them on a fork: https://github.com/magikstm/flight

Tested PHP:
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3

I think they would give useful info on tests and PHP versions.

There's a related PR here: https://github.com/mikecao/flight/pull/212

**Comment by mikecao** [comment]
I tried playing around with travis-ci and my build kept failing. Not sure what I'm doing wrong. Here is what I would see:

[![Build Status](https://travis-ci.org/mikecao/flight.svg?branch=master)](https://travis-ci.org/mikecao/flight)

The log from travis:

![image](https://user-images.githubusercontent.com/477975/57574465-77278480-73ee-11e9-9c4e-58c8117215e0.png)

**Comment by magikstm** [comment]
I submitted #393 for it.

You would need to adjust settings inside coveralls and travis-ci:
https://coveralls.io/sign-in (Github sign in, first red button in the middle)
https://travis-ci.org/ (Sign in with Github at the top)

By:
1) Logging-in with your github account
2) Linking your account inside both
3) Adding the repository inside both (your repositories will be listed in the first page after you log in)
4) Toggling the repository as active
5) Committing PR #393 

For Travis CI, toggling a repo is available in the Settings page available after you login in the top right corner under your name. The repository should be available on that page (you may need to scroll a bit).

For Coveralls, toggling a repo is available in the Add Repo page available after you login on the left under the available icons (it's the 2nd button). The repository should be available on that page (you may need to scroll a bit).

There are more options you could adjust, but default ones would be good at first.

Let me know if you need help setupping either.

**Comment by magikstm** [comment]
I believe the issue you are having is because of a missing or incorrect .travis.yml under the main folder of the repository. This issue should be corrected after you pull #393.

Travis-CI docs:
https://docs.travis-ci.com/user/languages/php/

Coveralls docs:
https://docs.coveralls.io/php
https://github.com/php-coveralls/php-coveralls

**Comment by n0nag0n** [comment]
Because this has aged a bit, lemme know if you still want/need this. We're slowly making our way to do it on our own.
