### ISSUE TITLE
JsonSerializable for util/Collection

### ISSUE THREAD

**Issue by merkuriy** [flightphp/core#394]
It will be useful to call json_encode directly for a `Collection` object, without an additional call to `Collection->getData()`.
 ́

**Example 1 - Current way**
```php
json_encode(Flight::request()->data->getData())
```

**Example 2 - New good way**
```php
json_encode(Flight::request()->data)
```
 ́

## Solution - Variant 1
**/flight/util/LegacyJsonSerializable.php**
```php
if (!interface_exists('JsonSerializable')) {
    interface JsonSerializable {
        public function jsonSerialize();
    }
}
```

**/flight/util/Collection.php**
```php
…
if (!interface_exists('JsonSerializable')) {
    require_once dirname(__FILE__) . '/LegacyJsonSerializable.php';
}
…
class Collection implements \ArrayAccess, \Iterator, \Countable, \JsonSerializable {
    …
    /**
     * Gets the collection data which can be serialized to JSON
     *
     * @return array Collection data which can be serialized by <b>json_encode</b>
     */
    public function jsonSerialize() {
        return $this->data;
    }
}
```
 ́

## Solution - Variant 2
Used
https://github.com/packfire/php5.3-compatibility/blob/1.0.0/src/JsonSerializable.php https://packagist.org/packages/packfire/php5.3-compat

**/composer.json**
```json
…
    "require": {
        "php": ">=5.3.0",
        "packfire/php5.3-compat": "1.0.0"
    },
…
```

**/flight/util/Collection.php**
```php
…
class Collection implements \ArrayAccess, \Iterator, \Countable, \JsonSerializable {
    …
    /**
     * Gets the collection data which can be serialized to JSON
     *
     * @return array Collection data which can be serialized by <b>json_encode</b>
     */
    public function jsonSerialize() {
        return $this->data;
    }
}

**Comment by merkuriy** [comment]
Do you like any of these solutions? I can make a Pull Request.

**Comment by mikecao** [comment]
I would rather not have any dependencies on composer so the first solution would be better. But I don't think you need to check `interface_exists` twice.
