### ISSUE TITLE
Flight::request()->scheme return SERVER_PROTOCOL and not REQUEST_SCHEME

### ISSUE THREAD

**Issue by hlidotbe** [flightphp/core#396]
`Flight::request()->scheme` does not return _http_ or _https_ as documented but the server protocol (which is almost always HTTP/1.1 and not the scheme).

`REQUEST_SCHEME` should be used instead of `SERVER_PROTOCOL`. `HTTP_X_FORWARDED_PROTO` should be handled if present instead of `REQUEST_SCHEME`

**Comment by pwFoo** [comment]
The PR is merged. So issue is fixed? Could be closed?

**Comment by hlidotbe** [comment]
Yes indeed
