### ISSUE TITLE
Return of Flight::json(Flight::request()->data) is empty?

### ISSUE THREAD

**Issue by pwFoo** [flightphp/core#400]
Should `Flight::json()` handle the `Flight::request()->data` object as input? At the moment the output is empty. I know it isn't sanitized by default, but that could be done by a hook and so it would be nice to just send it to `Flight::json()` to return valid json?

Or what is the Flight way to do it?

**Comment by mikecao** [comment]
You need to use `Flight::request()->data->getData()` to get the raw array that can be serialized.

**Comment by pwFoo** [comment]
Thanks, works fine!
