### ISSUE TITLE
Unable to get files

### ISSUE THREAD

**Issue by markusand** [flightphp/core#403]
I am not able to capture uploaded files from Flight::request()->files

```php
Flight::route('PUT /test', function() {
   $file = Flight::request()->files['upload'];
   Flight::json($file);  // or var_dump($file)
});
```
It seems it always receive and empty array.
I've tried sending file using Postman and using axios, but none of them is working:
```javascript
const file = target.files[0];
const data = new FormData();
data.append('upload', file, file.name);

axios.put('/test', data, { headers: { 'Content-Type': 'multipart/form-data;' } })
    .then(({ data }) => console.log('success', data))
    .catch(({ response: { data } }) => console.log('error', data));
```
Is there any kind of configuration that may be blocking it? 
There is very few documentation and examples on this.

**Comment by mikecao** [comment]
The request `files` is simply an abstraction over the global `$_FILES` variable which is provided by the server. For PUT requests you need to use the `getBody` method.

More info here, https://stackoverflow.com/questions/12005790/how-to-receive-a-file-via-http-put-with-php
