### ISSUE TITLE
[Info] Example Flight Application: FlightWiki

### ISSUE THREAD

**Issue by jonasgeiler** [flightphp/core#414]
Just wanted to let you know that I've developed a little example application for Flight.
It's called "FlightWiki" and is a super basic wiki.
You can find it [here](https://github.com/Skayo/FlightWiki)!
Could be a good source for some beginners maybe, so it would be awesome if you add a link to it somewhere in the README!

**Comment by n0nag0n** [comment]
Added to readme https://github.com/flightphp/core/commit/14afe68517bae5f8a00e9ec604fcb8e762d23426
