### ISSUE TITLE
Error on web hosting that related to inclusion

### ISSUE THREAD

**Issue by vic4key** [flightphp/core#426]
Hi @mikecao and everybody,

I got an error on web hosting, but running normal no error in AMPP or XAMPP on my machine.
I'm not used composer to install, just download and extract, using by `require_once "libraries/Flight/Flight.php";`
I already tried some way to fix but not successful (include trying with latest version).

The error is `Fatal error: Class 'flight\Engine' not found in /home/<user>/public_html/libraries/Flight/Flight.php on line 89`.

    /**
     * @return \flight\Engine Application instance
     */
    public static function app() {
        static $initialized = false;

        if (!$initialized) {
            require_once __DIR__.'/autoload.php';

            self::$engine = new \flight\Engine(); // this is line 89

            $initialized = true;
        }

        return self::$engine;
    }

Please help me to resolve this issue.

Thanks,
Vic P.

**Comment by magikstm** [comment]
Did you try doing the installation manually?

Ref: https://github.com/mikecao/flight

Flight should be available in the path listed in that line of your index.php:
require 'flight/Flight.php';

Did you manually upload it under that path which seems to be listed in the error above?
/home/<user>/public_html/libraries/Flight/Flight.php

**Comment by vic4key** [comment]
Yes, I upload it manually but the folder structure is the same as the project on my machine.
I don't know why the framework could not use the `Engine` module.

**Comment by vic4key** [comment]
I change the PHP version from 5.6 to 7.0 the error message is :(

`Fatal error: Uncaught Error: Class 'flight\Engine' not found in /home/<user>/public_html/libraries/Flight/Flight.php:89 Stack trace: #0 /home/<user>/public_html/libraries/Flight/Flight.php(75): Flight::app() #1 /home/<user>/public_html/commons/configures.php(75): Flight::__callStatic('map', Array) #2 /home/<user>/public_html/index.php(5): require_once('/home/<user>/...') #3 {main} thrown in /home/<user>/public_html/libraries/Flight/Flight.php on line 89`

That

.../configures.php(75): Flight::map(...)
.../index.php(5): require_once "commons/configures.php";

**Comment by vic4key** [comment]
Found the cause. My fault. Cuz I renamed `flight` to `Flight`. On windows, it's fine but on Linux web hosting, it will be file not found.
