### ISSUE TITLE
ETag not wrapped in double quotes

### ISSUE THREAD

**Issue by kuopassa** [flightphp/core#431]
`Flight::etag('test')` creates a header that's not wrapped in double quotes, but [this instructs](https://tools.ietf.org/html/rfc7232#section-2.3.1) ETag should do so.

**Comment by n0nag0n** [comment]
If it's standard, should be easy to add.

**Comment by n0nag0n** [comment]
Added it in with https://github.com/flightphp/core/commit/8d20c002c819df91b385ae3c3754b9466b2c786d

Also here's an MDN link https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
