### ISSUE TITLE
current url

### ISSUE THREAD

**Issue by oscarlosan** [flightphp/core#436]
Hello,
How can I get the current url?

try: Flight::route ();

**Comment by magikstm** [comment]
https://flightphp.com/learn#requests

$url = Flight::request()->query['url'];

or

$url = Flight::request()->query->url;

**Comment by oscarlosan** [comment]
magikstm thank you very much for the reply.
This framework is incredible. I am flying with this framework.
It is much better than F3 and Lumen. Super intuitive.

**Comment by oscarlosan** [comment]
what difference is there with:
Flight::router()->current ();
