### ISSUE TITLE
autoregister class

### ISSUE THREAD

**Issue by oscarlosan** [flightphp/core#437]
Hello,
Before with php and 1 line I already had the class instantiated:
1)$object = new Class;

with flightphp I have to do 2 lines for each instance:
1)Flight::register ('Class', 'Class');
2)$object = Flight::Class();

Is it possible to autoregister?

**Comment by magikstm** [comment]
https://flightphp.com/learn#frameworkinstance

**Comment by oscarlosan** [comment]
It is about the custom classes that I add to the framework. In the manual it says:

Registering Classes
---------------
To register your own class, you use the register function:

// Register your class
1) Flight :: register ('user', 'User');

// Get an instance of your class
2) $user = Flight :: user ();

**Comment by magikstm** [comment]
FlightPHP is a framework, so there are a few more lines required.

**Comment by oscarlosan** [comment]
It would be interesting if the Class class would be automatically registered when you do this:
$ object = Flight :: Class ();
1 single line and it is also prevented from registering classes that we don't use later.

**Comment by oscarlosan** [comment]
it is torture having to add 2 lines for each class in my application. Self-registration. 
Even if it is by configuration variable.
please.

**Comment by mikecao** [comment]
It is not possible to auto register because how would PHP even know what classes to register?

But also you don't have to register all your classes. It's just a convenience method, but you can declare your classes like normal.

**Comment by oscarlosan** [comment]
By the name of the class you will know if it has to be registered or is already registered. (without the framework it is not necessary to register them).

ok class errors stopped when adding this line: Flight :: set ('flight.handle_errors', false);

thanks for the support.
