### ISSUE TITLE
code reduction with parameters

### ISSUE THREAD

**Issue by oscarlosan** [flightphp/core#443]
```
class Greeting {
    public static function hello($params) {
        echo 'hello '.$params['planet'].'!';
    }
}
```

//it would be interesting to be able to pass parameters. It would reduce my code by 30%. All in the same line:

`Flight::route('/', array('Greeting','hello', ['planet' => 'Earth']));`

**Comment by paxperscientiam** [comment]
Perhaps you could try overriding the router. See here: https://flightphp.com/learn#overriding

**Comment by masroore** [comment]
If your controller methods need static parameters, then you may rethink your code design. The default router is optimized for capturing user-supplied dynamic inputs.

**Comment by n0nag0n** [comment]
> If your controller methods need static parameters, then you may rethink your code design. The default router is optimized for capturing user-supplied dynamic inputs.

I agree, I think that this isn't the way to go with the framework moving forward, but appreciate the feedback! Overriding is probably your best bet.
