### ISSUE TITLE
Unable to load static files while using route with parameter

### ISSUE THREAD

**Issue by Sokhavuth** [flightphp/core#448]
Static files are not loaded while using route with parameter. In Node.js and in Python, every framework gives us the options to choose folder for "views" and static files such as css, js, and image files. In those frameworks, the default folders for views and static files are "views" and "public". And without static files, there won't be template.

**Comment by mfrederico** [comment]
This sounds like a webserver configuration issue, not a flightphp issue.

**Comment by n0nag0n** [comment]
Yes, this is a webserver issue, not a framework issue. Flight wasn't meant to handle service static content because webservers do this in a **way** more efficient way.
