### ISSUE TITLE
Custom 404 page return 200

### ISSUE THREAD

**Issue by lk-KEVIN** [flightphp/core#453]
Hi, I was trying to use a custom html file to replace the default error page, but the body returns 200 OK instead of 404 Not Found.
Tried the code for issue #343 and everything was fine, return 404

```php
Flight::route('/status', function() {
    Flight::response()->status(404);
    echo 'The status is 404.';
});
```

then I try to [Override](https://flightphp.com/learn#overriding) using the example from the docs is when return 200 OK

```php
Flight::map('notFound', function(){
    // Display custom 404 page
    include 'errors/404.html';
});
```
What should I do?
neither `http_response_code(404);`, `header("HTTP/1.1 404 Not Found");` or Apache `ErrorDocument 404 errors/404.html` return 404 Not Found

My only solution is replace the original [flight\Engine.php](/mikecao/flight/blob/master/flight/Engine.php#L442) error message

**Comment by severak** [comment]
Hi, this works for me:

```
Flight::map('notFound', function(){
	Flight::response(false)
            ->status(404)
            ->write(
                file_get_contents(__DIR__ . '/lib/views/404.htm')
            )
            ->send();
});
```

**Comment by sah-comp** [comment]
You may also use:

```
Flight::stop(404);
```

**Comment by krmu** [comment]
Or you can use 
`Flight::halt(404, 'Not found');`

@n0nag0n  also can be closed.

**Comment by n0nag0n** [comment]
Thanks @krmu
