### ISSUE TITLE
Performance: Cached Routes + opcache

### ISSUE THREAD

**Issue by ghost** [flightphp/core#462]
Is it possible to cache the current routes? For max performance?

Examples: 
1. https://github.com/nikic/FastRoute#caching
2. https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Console/RouteCacheCommand.php

**Comment by ghost** [comment]
Any suggestion @mikecao?

**Comment by magikstm** [comment]
Opcache should work with Flight.

Flight is really light.

Other things such as database or dynamic content would probably be the performance bottleneck.

**Comment by n0nag0n** [comment]
If you have a large amount of routes, then caching is beneficial. If you only have a couple dozen, it's basically worthless. When you have 100s of routes then caching becomes amazing!

Closing for now.
