### ISSUE TITLE
Trying to use Jquery with Flight

### ISSUE THREAD

**Issue by Flashtheorie** [flightphp/core#466]
I'm developing something where I need to use jquery using .load() but it loads a 404, I tried creating a route, but then it doesn't load the page at all

`$("#photos1").load("photosun");`

`
Flight::route('/photosun', function(){ 
    require 'views/affichagephotos1.php';
});
`

**Comment by magikstm** [comment]
Could you please share more code related to your issue?

Depending where the related page is, you may need to adjust the line:
`$("#photos1").load("photosun");`

Do either the 1st or the 2nd line work if you visit the pages directly?

**Comment by Flashtheorie** [comment]
basically, it's a face mash clone where you click on your favorite picture and it loads again another picture after adding a vote to it

**Comment by Flashtheorie** [comment]
So, you were right, I had an error on the page, that's why it wasn't loading
Thank you !
