### ISSUE TITLE
Routes other than `/` don't work

### ISSUE THREAD

**Issue by ehsanghorbani190** [flightphp/core#472]
Hi! this is my `index.php` file:
```PHP
<?php
require 'vendor/autoload.php';

Flight::route("/atu" , function(){
	echo "HI";
});
Flight::route('/', function(){
    echo 'hello world!';
});


Flight::start();
```
and this is my `.htaccess` file:
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]
```
and this is what i get when i try to access `localhost/atu`:
![image](https://user-images.githubusercontent.com/35449522/182010498-790fffd0-56ea-4c7c-aeac-79c2bd345742.png)

Where's the problem?!

Update: I just tested it on a server and it works fine, but i cant use it on my local machine.

**Comment by kuopassa** [comment]
Is your website on localhost available directly at http://localhost, or is it in subfolder, like http://localhost/atu/? If it's the latter, then you might need to add this to your .htaccess file below `RewriteEngine On`:

`RewriteBase /atu/`

**Comment by paxperscientiam** [comment]
Check the server logs.

EDIT: Also, all of those htaccess rules can be replaced with this:
`FallbackResource /index.php # or whatever your main file is called`

**Comment by krmu** [comment]
@ehsanghorbani190 does this problem still exists?

**Comment by ehsanghorbani190** [comment]
@krmu honestly I don't know. I've moved from that project and also PHP.
