### ISSUE TITLE
Using Request Object

### ISSUE THREAD

**Issue by tyfai** [flightphp/core#480]
Is using the request object mandatory?

At the moment I am using the traditional `$_GET`, `$_POST`, `$_FILES`, and `$_SESSION` variables.

Everything seems to be working, but should I use `Flight::request()` instead?

**Comment by pierresh** [comment]
This is not mandatory but much cleaner to use data from `Flight::request()`, that is not really good to use super globals directly :)

**Comment by tyfai** [comment]
Okay, thank you.

I will leave the existing code alone, but going forward I will use `Flight::request()`. :)
