### ISSUE TITLE
Route preg_match() error

### ISSUE THREAD

**Issue by oscarlosan** [flightphp/core#482]
if i add this route
`Flight::route('/', function(){
    echo 'hello world!';
});`
I get this error:
[2] preg_match(): Compilation failed: range out of order in character class at offset 39
en la línea 132 en el archivo C:\xampp\htdocs\pb.com\_beta3\codecore\flight\net\Route.php

Note: I am using php 7.4.27 and Flight 2.0.1

**Comment by n0nag0n** [comment]
Could you retry this now with the new updates? I'm thinking it's your environment issue because that is such a basic route. There's a chance your PCRE didn't compile correctly on your windows environment.
