### ISSUE TITLE
I make a new framework ‘Alight’, can anyone try it and give me some feedback?

### ISSUE THREAD

**Issue by juneszh** [flightphp/core#495]
Hello everyone, I have been using ‘Flight’ for many years, perhaps as early as 2016. I would like to thank ‘Flight’ for helping me complete many project developments and learn a lot of solutions from the source code.

Since the version updates of ‘Flight’ have gradually decreased in recent years, and I also have some new ideas about the framework, I tried to create a new light-weight php framework [Alight](https://github.com/juneszh/alight) myself.

After more than a year of use and optimization in production projects, 'Alight' has become more and more stable, so version 2.0 was recently released. I hope more people can try it or give me suggestions.

Hi @mikecao, I don’t know if it’s right to post it here. If it offends you, please tell me and I will delete it immediately.

**Comment by n0nag0n** [comment]
I think it's a cool little project, but not sure why you posted in the Flight repo for it since it doesn't use Flight? You could start a discussion on this if you'd like some feedback on it, I'm just trying to groom some old issues for the time being.

Thanks!
