### ISSUE TITLE
Migrate to Flight 2

### ISSUE THREAD

**Issue by cafe24-jhjeong02** [flightphp/core#497]
I'm planning to migrate from Flight 1 to Flight 2 for PHP 8 compatibility. Where can I see the list of breaking changes I should take care of?

**Comment by mjisoton** [comment]
As far as I know, FlightPHP kept all methods and behaviour from the previous version, so there's no breaking changes on the framework itself. 
Obviously, that do not apply to your own code, so you should check your controllers (routes) and extensions (extended and mapped methods). 

The list of backward incompatible changes and deprecated functions from PHP 7.x to PHP 8.0.x is [here](https://www.php.net/manual/en/migration80.php).
