### ISSUE TITLE
Naming routes - help for navigation

### ISSUE THREAD

**Issue by krmu** [flightphp/core#502]
Hello!

We recently resolved an issue, but now I'm facing trouble with navigation. Although I've set up all the routes, manually coding URLs in the navigation is becoming cumbersome. Whenever there's a URL change, I have to go through the entire codebase to update the hardcoded URLs.

I'm not sure if this is related to issue #487.
My suggestion is to create a function like:
`Flight::getRoute('user_dashboard');`
This function would return the full path of the specified route. If the route has parameters, we could use it like this:
`Flight::getRoute('user_dashboard', ["param1" => 1234]);`

Ideas?

**Comment by magikstm** [comment]
What do you mean by:
"I have to go through the entire codebase to update the hardcoded URLs"

Could you possibly share one of your recent change that was "cumbersome"?

**Comment by n0nag0n** [comment]
I know what you're talking about. I added this to the project list cause I feel this is important as well. https://github.com/orgs/flightphp/projects/1/views/1?pane=issue&itemId=49025073

**Comment by n0nag0n** [comment]
https://github.com/flightphp/core/pull/510 Feedback helpful :)

**Comment by krmu** [comment]
Fixed in the last release 3.0.2.
