### ISSUE TITLE
Possible integration with Roadrunner and Swoole.

### ISSUE THREAD

**Issue by iamkarshe** [flightphp/core#507]
Roadrunner is a high-performance PHP application server, load-balancer, and process manager written in Golang.

Integration existing FlightPHP application with Roadrunner would provide faster throughput. 

https://roadrunner.dev/
https://openswoole.com/

**Comment by n0nag0n** [comment]
Oh I'm super on board with this, I just think that this will take more massaging to get to that point. I've done this for Fat-Free in https://github.com/n0nag0n/fatfree-swoole. My goal is to get flight to that point, but it's not the goal right now.

**Comment by n0nag0n** [comment]
If you want, you could fork core and make changes to see if you can get swoole running properly and then based on what you learn I could make the changes in core to handle a swoole/roadrunner/workerman/reactphp implementation. You could base it off of my fat-free swoole project, and I based that a lot off of https://github.com/pachico/slim-swoole which is now archived. It would just help save me a step of figuring out what needs to be unset/reset/rebuilt to work with swoole or some other framework.
