### ISSUE TITLE
Possible deployment on AWS Lambda.

### ISSUE THREAD

**Issue by iamkarshe** [flightphp/core#509]
Providing script or readme on how to deploy FlightPHP app on AWS Lambda with full compatibility. 

Some help / example we can take help from
- https://medium.com/artisanhost/hosting-a-laravel-application-on-aws-lamdba-90b7133c8578
- https://adevait.com/laravel/deploying-laravel-api-on-aws-lambda

Auto-deployment with FlightPHP's CLI tool like `artisan` (let's name it `launcher`) via 
`launcher deploy aws-lambda -c config.yml`

**Comment by n0nag0n** [comment]
haha, this could be useful but way out of my scope to look into. If you want to come together with something on it, I can look it over and add it to maybe the flightphp.com documentation! There's just a lot of fish to fry at the moment with the framework :sweat_smile:
