### ISSUE TITLE
[Views]  register method : no autocomplete / intelsense

### ISSUE THREAD

**Issue by ampmonteiro** [flightphp/core#563]
Hi,

please add comment for the  `register` method on  `Flight` class.

And another thing, as you can see on the image the `Dispatcher` class is not being used, please remove it.

Thanks

![image](https://github.com/flightphp/core/assets/31895754/685f0075-5af9-4ed9-b519-766da8d149a7)

**Comment by n0nag0n** [comment]
So I mean I can absolutely do this, but removing a line, and adding another one is a really easy PR to make and then you get some legit street cred that you contributed to the framework :)

**Comment by ampmonteiro** [comment]
Hi,

i think it is more work than you do yourself.

Feel free  to do it,  i did not  do this issue to  gain some cred.

Thanks anyways e can close the issue.

**Comment by n0nag0n** [comment]
I fixed it for you. You'll regret not having cred :rofl:
