### ISSUE TITLE
How to stop the request process when there is an issue in the Middleware?

### ISSUE THREAD

**Issue by pamungkasandono** [flightphp/core#582]
When I try to validate the token in the middleware, the output generated is not as expected. Here's an example of the middleware I created:

```php
class AuthMiddleware
{
    public function before($params)
    {
        $token = Flight::request()->getHeader("Authorization");
        if (!$token) {
            return Flight::json([
                "message" => "Token required!."
            ], 400);
        }
    }
}

Flight::route('/', function () {
    return Flight::json([
        "message" => "Success."
    ], 200);
})->addMiddleware(new AuthMiddleware());
```

If I don't send the token in the header, the expected output should be:

```php
{
    "message": "Token required!."
}
```

But in this case, why is the output:
```php
{
    "message": "Token required!."
}{
    "message": "Success."
}
```

Could you please assist me? Is there something missing?

**Comment by n0nag0n** [comment]
My guess is you would do 
```php
if (!$token) {
    echo Flight::json([
        "message" => "Token required!."
    ], 400);
    return false; // add this line.
}
```

**Comment by pamungkasandono** [comment]
Thank you for your response.

When I tried using ```return false``` the return response, what I received is:

```html
Forbidden
```

![image](https://github.com/flightphp/core/assets/55474559/159905bd-6921-46cc-bdb3-2e3393530d00)

Do you have any other suggestions?

**Comment by krmu** [comment]
Instead of return false, try exit();

**Comment by krmu** [comment]
Worked for me, redirects were acting strange.

**Comment by n0nag0n** [comment]
Ahh yeah, like @krmu mentioned, I would either directly use `exit;` to stop execution.

**Comment by n0nag0n** [comment]
@pamungkasandono I've updated the documentation to be more clear about what behavior to expect. https://docs.flightphp.com/learn/middleware#handling-middleware-errors

**Comment by pamungkasandono** [comment]
@krmu my middleware is now working as expected with the addition of ```exit();```. @n0nag0n documenting this would be really helpful for other. Thanks, everyone! I truly appreciate it!

**Comment by n0nag0n** [comment]
Thinking more about this along with some other things that have surfaced, I came up with this PR. https://github.com/flightphp/core/pull/594 Would love your feedback.

So in this case you would just do 

```php
Flight::jsonHalt([
    "message" => "Token required!."
], 400);
```

No `exit`, no `Flight::halt()` method. It would immediately stop execution on that line.
