### ISSUE TITLE
Wrong request method response

### ISSUE THREAD

**Issue by luka97zr** [flightphp/core#590]
**Is your feature request related to a problem? Please describe.**
If the request is sent to the existing route but with the wrong method provided, the 404 page is returned by default.

**Describe the solution you'd like**
It would be more helpful if the response pointed out that the method is wrong rather than returning the default 404 page.

**Additional context**
If a GET request is sent to an existing route that accepts the POST method, the 404 page is returned instead of the wrong method response.

**Comment by n0nag0n** [comment]
How's this? https://github.com/flightphp/core/pull/591

**Comment by n0nag0n** [comment]
Merged to master. Will be included in next release.
