### ISSUE TITLE
Including version number of Flight in Flight.php root file

### ISSUE THREAD

**Issue by mrijntjes** [flightphp/core#592]
It would be great if the version number of Flight could be included in the Flight.php file. This makes it easy to check which version you are using.

Thanks by the way for making Flight.php, i'm using Flight many years.

![afbeelding](https://github.com/flightphp/core/assets/49949388/96abbe14-2862-4100-b841-1746026a1913)

**Comment by n0nag0n** [comment]
So you just want it in a comment like that? What's your use case for it? I just assume you could just run `composer show flightphp/core` and get your version there.

And you're welcome! Flight is a really fun framework!

**Comment by mrijntjes** [comment]
Thanks for your reply. I'm not using composer, but downloaded the php files of Flight straight from this repository. But thanks for hinting me to composer!

**Comment by n0nag0n** [comment]
You're welcome! We really strive to not include additional dependencies with this library. There are some in the dev version for composer so that proper unit testing can happen.

Tell your friends about Flight! :rocket:
