### ISSUE TITLE
How to show custom page for 500 error?

### ISSUE THREAD

**Issue by goigarg** [flightphp/core#593]
If there is an error in code it just show HTTP ERROR 500

how do I make a custom html page for that ?

**Comment by n0nag0n** [comment]
You can see here in the docs, this is how you'd handle a not found error (404). In this case you would do something like `Flight::map('error', function(Throwable $error) { /* code here */ });` instead.

https://docs.flightphp.com/learn/extending#overriding-framework-methods

**Comment by krmu** [comment]
And there comes example from our tests folder.
https://github.com/flightphp/core/blob/10165ebda34357fc7a92dacf6c076ee957629f4f/tests/server/index.php#L174
