### ISSUE TITLE
ControllerCommand uses Nette\PhpGenerator but that dependency is not declared in composer.json

### ISSUE THREAD

**Issue by lubiana** [flightphp/core#604]
**Describe the bug**

**To Reproduce**
- clone current git master
- composer install
- composer test

**Expected behavior**
The tests run successfully

**Actual behavior**
ControllerCommandTest fails, and notes that the files does not exist.
When stepdebugging we can find out, that it boils down to a class not found error for Nette\PhpGenerator

**Environment (please complete the following information):**
 - OS: Linux
 - PHP Version: 8.3
 - Flight Version: current master

**Comment by n0nag0n** [comment]
So I see your point, but here me out on this one.

It is required through require-dev in composer through flightphp/runway. Why I thought that was ok was typically you aren't going to be running `runway` commands in production, but instead on your development environments. If the argument is that runway should also work in production then we probably should move that flightphp/runway to production, but that would add a dependency to the core. One other option is that we could put the ControllerCommand and the other commands in runway itself, or in another package altogether to keep core dependency free. 

Thoughts?

**Comment by lubiana** [comment]
the current composer.json in the master branch requires runway in version 0.2.0, the php-generator dependency was only added in runway 0.2.2, so maybe we should bump the dependency requirement for runway to a newer version?

edit:
and yes, i am absolutety fine with requiring runway (and therefore php-generator), but we need to make shure, that the tests do not fail when installing the dependencies as declared in composer.json

**Comment by n0nag0n** [comment]
This is now updated and pushed to master. Thanks so much!
