### ISSUE TITLE
custom page for http errors also

### ISSUE THREAD

**Issue by abda11ah** [flightphp/core#611]
Hi,
I saw in the source code that many http errors are directly returned as english messages like "403 unauthorized or 503 ressource unavailable  etc..."

I already defined a custom template for exception errors but these errors are not rendered with it.

**Comment by n0nag0n** [comment]
Can you give me some example of how you're trying to implement it? If it's what I'm thinking, Are you referring to the `Response::$codes` static array with all the messages there? If that's true can you show me how you're trying to override it?

**Comment by abda11ah** [comment]
Sorry i'm not currently using this.
I just saw static "header('Location:' .....410) functions in source code.....

**Comment by n0nag0n** [comment]
So is there something that still needs to be fixed if you aren't using it anymore?

**Comment by abda11ah** [comment]
I'm currently developing a dating website with the help of bolt AI that is based on Flightphp and Cash.js.
I have many other priorities, but as I've planned the website to be multilingual, it surprised me to see static error messages in a framework without the possibility of returning them to a custom page.

**Comment by n0nag0n** [comment]
So you can actually overwrite the error method with any error that is thrown and you can put it through whatever mechanism you have for multiple languages. 
https://docs.flightphp.com/learn/extending#overriding-framework-methods

Here's the list of extendable methods:
https://docs.flightphp.com/learn/api

**Comment by n0nag0n** [comment]
Assuming this is fixed.

**Comment by abda11ah** [comment]
I completely dropped FlightPHP from the website.
I'm trying to rebuild all the website from a tiny router + a PSR11 container class.
